/* Actual worker evaluated in a deterministic browser-API harness, not a browser. */
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{webcrypto}=require('node:crypto');
const root=path.resolve(__dirname,'../..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'paper-offline-'));
const origin='https://paper.test',scope=origin+'/Paper/';
const stores=new Map();let quota=false,offline=false,failPath='',badPath='',reads=[],writes=0;
const key=x=>typeof x==='string'?x:x.url;
class Cache {constructor(){this.rows=new Map();}async match(r){return this.rows.get(key(r))?.clone();}async put(r,s){if(quota)throw new DOMException('synthetic quota','QuotaExceededError');this.rows.set(key(r),s.clone());writes++;}async keys(){return [...this.rows.keys()].map(x=>new Request(x));}async delete(r){return this.rows.delete(key(r));}}
const caches={async open(n){if(!stores.has(n))stores.set(n,new Cache());return stores.get(n);},async keys(){return [...stores.keys()];},async delete(n){return stores.delete(n);}};
function fixture(name,version,asset){const dir=path.join(temp,name);fs.mkdirSync(path.join(dir,'library','fixture'),{recursive:true});fs.mkdirSync(path.join(dir,'downloads'));fs.writeFileSync(path.join(dir,'index.html'),'<p>'+version+'</p>');fs.writeFileSync(path.join(dir,'release.json'),JSON.stringify({version,sourceCommit:'synthetic-only'}));fs.writeFileSync(path.join(dir,'library/fixture/source.pdf'),asset);fs.writeFileSync(path.join(dir,'downloads/source.zip'),'ZIP:'+asset);fs.writeFileSync(path.join(dir,'data.json'),'{}');execFileSync('python',['-c',`import sys;sys.path.insert(0,'scripts');from seal_site import seal;seal(${JSON.stringify(dir)})`],{cwd:root});return dir;}
const v1=fixture('v1','one','0123456789ABCDE'),v2=fixture('v2','two','abcdefghijklmno');let served=v1;
async function fetcher(request){const u=new URL(key(request));reads.push(u.pathname);if(offline||u.pathname===failPath)throw new TypeError('synthetic network interruption');const name=decodeURIComponent(u.pathname.replace('/Paper/',''));const p=path.join(served,name);if(!fs.existsSync(p))return new Response('not found',{status:404});let data=fs.readFileSync(p);if(u.pathname===badPath)data=Buffer.alloc(data.length,88);return new Response(data,{headers:{'Content-Type':name.endsWith('.json')?'application/json':'application/octet-stream','Content-Length':String(data.length)}});}
function worker(dir){const listeners=new Map();const self={registration:{scope},clients:{claim:async()=>{},matchAll:async()=>[]},skipWaiting:async()=>{},addEventListener:(n,fn)=>{if(!listeners.has(n))listeners.set(n,[]);listeners.get(n).push(fn);}};const context=vm.createContext({self,caches,fetch:fetcher,crypto:webcrypto,URL,Request,Response,Headers,Blob,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,AbortController,MessageChannel,DOMException,setTimeout,clearTimeout,setInterval,clearInterval,console});vm.runInContext(fs.readFileSync(path.join(dir,'sw.js'),'utf8'),context);
 const emit=async(type,event)=>{const waits=[];event.waitUntil=p=>waits.push(p);for(const fn of listeners.get(type)||[])fn(event);await Promise.all(waits);};
 return {context,install:()=>emit('install',{}),async message(type,extra={}){const messages=[];await emit('message',{data:{type,...extra},ports:[{postMessage:x=>messages.push(x)}]});return {messages,result:messages.at(-1)};},async get(name,headers={}){let response;await emit('fetch',{request:new Request(scope+name,{headers}),respondWith:p=>response=p});return response?await response:null;}};}
(async()=>{try{
 const foreign=await caches.open('paper-lab:/Farm/:foreign');await foreign.put(origin+'/Farm/sentinel',new Response('farm'));
 const privateState={notes:'synthetic private note',imports:'synthetic imported paper',translation:'synthetic reviewed translation'};const saved=JSON.stringify(privateState);
 const a=worker(v1);await a.install();assert.equal((await a.message('STATUS')).result.complete,false);
 failPath='/Paper/downloads/source.zip';let failed=await a.message('CACHE_ALL');assert.equal(failed.result.complete,false);assert(failed.result.failed.some(x=>x.url.endsWith('.zip')));assert(failed.messages.some(x=>x.type==='PROGRESS'&&x.verifiedBytes>0));
 const retained=(await caches.open('paper-lab:/Paper/:sha256-v3')).rows.size;assert(retained>=4);failPath='';reads=[];
 const resumed=worker(v1);const together=await Promise.all([resumed.message('CACHE_ALL'),resumed.message('CACHE_ALL')]);assert(together.every(x=>x.result.complete));assert.equal(reads.filter(x=>x==='/Paper/downloads/source.zip').length,1,'Repeated full-cache commands must coalesce');assert(!reads.includes('/Paper/library/fixture/source.pdf'),'verified files survive worker restart without re-download');
 assert.equal((await resumed.message('STATUS_FAST')).result.verification,'inventory-only');assert.equal((await resumed.message('STATUS_FAST')).result.complete,false);
 offline=true;assert.equal(await (await resumed.get('downloads/source.zip')).text(),'ZIP:0123456789ABCDE');assert.equal(await (await resumed.get('data.json')).text(),'{}');
 let range=await resumed.get('library/fixture/source.pdf',{Range:'bytes=2-5'});assert.equal(range.status,206);assert.equal(await range.text(),'2345');range=await resumed.get('library/fixture/source.pdf',{Range:'bytes=-3'});assert.equal(await range.text(),'CDE');assert.equal((await resumed.get('library/fixture/source.pdf',{Range:'bytes=90-100'})).status,416);
 assert.equal(await resumed.get('../Farm/sentinel'),null);assert.equal(await (await foreign.match(origin+'/Farm/sentinel')).text(),'farm');
 const lib=await caches.open('paper-lab:/Paper/:sha256-v3'),m1=JSON.parse(fs.readFileSync(path.join(v1,'offline-manifest.json'))),pdf1=m1.resources.find(x=>x.url.endsWith('.pdf')),pdfKey=scope+'.paper-offline/sha256/'+pdf1.sha256;
 await lib.put(pdfKey,new Response('XXXXXXXXXXXXXXX'));assert.equal((await resumed.message('STATUS')).result.complete,false,'Same-size corruption must not pass an existence receipt');offline=false;assert.equal((await resumed.message('CACHE_ALL')).result.complete,true);
 await lib.put(pdfKey,new Response('truncated'));assert.equal((await resumed.message('STATUS')).result.complete,false);assert.equal((await resumed.message('CACHE_ALL')).result.complete,true);
 served=v2;const oldCacheNames=await caches.keys(),legacy=await caches.open('paper-lab:/Paper/:source-library-v2');await legacy.put(scope+'library/fixture/source.pdf',new Response('0123456789ABCDE'));
 const b=worker(v2);await b.install();badPath='/Paper/library/fixture/source.pdf';let wrong=await b.message('CACHE_ALL');assert.equal(wrong.result.complete,false,'Same URL stale legacy or corrupt HTTP body cannot count for new version');badPath='';
 quota=true;const q=await b.message('CACHE_ALL');assert.equal(q.result.complete,false);assert(q.result.failed.some(x=>x.error.includes('Quota')));quota=false;
 for(const n of oldCacheNames)assert(stores.has(n),'Failed new generation must not delete old caches');
 offline=true;assert.equal(await (await a.get('library/fixture/source.pdf')).text(),'0123456789ABCDE','Old installed release remains readable after failed upgrade');offline=false;
 const finished=await b.message('CACHE_ALL');assert.equal(finished.result.complete,true);assert.equal(await (await b.get('library/fixture/source.pdf')).text(),'abcdefghijklmno');assert.equal(JSON.stringify(privateState),saved);assert.equal(await (await foreign.match(origin+'/Farm/sentinel')).text(),'farm');
 const m2=JSON.parse(fs.readFileSync(path.join(v2,'offline-manifest.json'))),manifestCacheName=(await caches.keys()).find(n=>n.includes('manifest-v3:')&&stores.get(n).rows.has(scope+'offline-manifest.json')&&n!==oldCacheNames.find(x=>x.includes('manifest-v3:')));
 // Alter non-pin SW bytes without touching the manifest; exact control validation rejects it.
 const controlCache=await caches.open(manifestCacheName);await controlCache.put(scope+'sw.js',new Response(fs.readFileSync(path.join(v2,'sw.js'),'utf8').replace('use strict','use Strict')));assert.equal((await b.message('STATUS')).result.complete,false);
 assert.equal((await b.message('CACHE_ALL')).result.complete,true);
 const brokenControl=Buffer.from(fs.readFileSync(path.join(v2,'sw.js')));brokenControl[0]=255;await controlCache.put(scope+'sw.js',new Response(brokenControl));assert.equal((await b.message('STATUS')).result.complete,false);assert.equal((await b.message('CACHE_ALL')).result.complete,true,'invalid UTF-8 controls remain repairable');
 await controlCache.delete(scope+'offline-manifest.json');assert.equal((await b.message('STATUS')).result.complete,false,'deleted manifest cannot count complete');assert.equal((await b.message('STATUS_FAST')).result.previouslyVerified,false);assert.equal((await b.message('CACHE_ALL')).result.complete,true,'deleted manifest can be restored from pinned bytes');
 await controlCache.put(scope+'offline-manifest.json',new Response('{}'));assert.equal((await b.message('STATUS')).result.complete,false);assert.equal((await b.message('CACHE_ALL')).result.complete,true);
 // This harness does not expose IndexedDB/localStorage: touching private stores fails by construction.
 console.log(JSON.stringify({status:'passed',checks:['interruption/resume across worker restart','byte progress','duplicate CACHE_ALL coalescing','offline ZIP and JSON','PDF normal/suffix/invalid ranges','exact-scope isolation','same-size/truncated cached corruption','same-URL changed release bytes','quota failure with recoverable retry','old-cache integrity after failed upgrade','canonical worker controls','no private storage API used'],browser:false,writes}));
 }finally{fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
