#!/usr/bin/env python3
"""Actual isolated Chromium UI QA. Requires the repository's playwright==1.55.0.

No private inputs, external websites, sockets/server, or note storage. A working
Chromium launch is required; never report these checks as passed if blocked.
"""
import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT = Path(__file__).resolve().parents[2]
OUT = Path(os.environ.get('RW_QA_DIR', str(ROOT / 'test-results' / 'walkthrough')))
OUT.mkdir(parents=True, exist_ok=True)
checks, errors, requests = [], [], []

def check(name, ok):
    assert ok, name
    checks.append(name)
    print('PASS', name)

def boot(browser, **options):
    context = browser.new_context(viewport={'width': 1100, 'height': 1000}, **options)
    page = context.new_page()
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.on('request', lambda r: requests.append(r.url))
    page.clock.install()
    page.set_content('<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>Isolated Paper walkthrough QA</title></head><body><main class="reader" style="max-width:860px;margin:auto;padding:12px"><p id="original-block" class="prose">Original preserved paragraph.</p><textarea id="private-note">Synthetic private note sentinel</textarea><section id="research-walkthrough"></section></main></body></html>')
    for name in ['style.css', 'research-walkthrough.css']:
        page.add_style_tag(content=(ROOT / 'src' / name).read_text())
    page.add_script_tag(content=(ROOT / 'src/research-walkthrough.js').read_text())
    page.evaluate('window.controller=PaperWalkthrough.mount(document.querySelector("#research-walkthrough"))')
    return context, page

def state(page): return page.evaluate('controller.getState()')
def step(page, n): page.locator(f'[data-step="{n}"]').click()
def click(page, action): page.locator(f'[data-action="{action}"]').click()
def set_range(page, key, value):
    page.locator(f'[data-field="{key}"]').evaluate('(el,value)=>{el.value=value;el.dispatchEvent(new Event("input",{bubbles:true}))}', str(value))
def busy(page): return page.evaluate('PaperWalkthrough.isBusy()')
def text(page, selector='.rw-stage'): return page.locator(selector).inner_text()

with sync_playwright() as pw:
    opts = {'headless': True}
    if os.environ.get('PW_EXECUTABLE_PATH'): opts['executable_path'] = os.environ['PW_EXECUTABLE_PATH']
    browser = pw.chromium.launch(**opts)
    try:
        context, p = boot(browser)
        p.clock.fast_forward(60000)
        check('No autoplay or timer on initial mount', state(p)['step'] == 0 and not state(p)['pendingTimer'] and not busy(p))
        p.evaluate('PaperWalkthrough.mount(document.querySelector("#research-walkthrough"))')
        check('Mounting twice creates only one panel', p.locator('.paper-walkthrough').count() == 1)
        check('Original paragraph and synthetic note remain unchanged', p.locator('#original-block').text_content() == 'Original preserved paragraph.' and p.locator('#private-note').input_value() == 'Synthetic private note sentinel' and p.locator('.paper-walkthrough .prose').count() == 0)
        p.locator('[data-field="costAW"]').fill('600')
        check('Modified input defers an automatic update', busy(p))
        step(p, 2)
        check('Raw seasonal cost propagates into annual margin', '2,300' in text(p))
        step(p, 4)
        check('The same raw input propagates into the main Pareto frontier', 'F1={A}' in text(p))
        click(p, 'reset')
        check('Reset clears modified and reading state', not busy(p) and state(p)['step'] == 0)
        p.locator('[data-field="costAW"]').fill('-1')
        check('Out-of-bounds input is marked invalid and keeps last valid number', p.locator('[data-field="costAW"]').get_attribute('aria-invalid') == 'true' and state(p)['values']['costAW'] == 1000 and p.locator('[data-action="play"]').is_disabled())
        p.locator('[data-field="costAW"]').fill('')
        check('Empty input never silently becomes zero', state(p)['values']['costAW'] == 1000)
        p.locator('[data-field="costAW"]').fill('1010')
        check('Valid input recovers without reset', state(p)['values']['costAW'] == 1010 and not p.locator('[data-action="play"]').is_disabled())
        p.locator('[data-field="costAW"]').fill('')
        click(p, 'reset')
        check('Reset clears a pending invalid input and playback block', not busy(p) and not p.locator('[data-action="play"]').is_disabled())
        click(p, 'next')
        check('Manual single-step advances', state(p)['step'] == 1)
        click(p, 'previous')
        p.locator('.paper-walkthrough').focus()
        p.keyboard.press('ArrowRight')
        check('Keyboard arrow moves a focused panel', state(p)['step'] == 1)
        for stage, selector in [(0, '.rw-table-wrap'), (4, '.rw-chart-scroll')]:
            step(p, stage)
            scroller = p.locator(selector).first
            scroller.focus();scroller.press('ArrowRight')
            check('Native scroller keeps arrow keys: '+selector, state(p)['step'] == stage)
        step(p, 1)
        slider = p.locator('[data-field="waterAW"]')
        slider.focus()
        slider.press('ArrowRight')
        check('Slider keyboard edits preserve focus and do not change stage', state(p)['step'] == 1 and state(p)['values']['waterAW'] == 305 and slider.evaluate('(el)=>el===document.activeElement'))
        click(p, 'reset')
        click(p, 'play')
        p.clock.fast_forward(12001)
        check('Requested playback advances after the chosen interval', state(p)['step'] == 1 and state(p)['playing'])
        click(p, 'play')
        before = state(p)['step']
        p.clock.fast_forward(60000)
        check('Pause stops timers and preserves the current step', state(p)['step'] == before and not state(p)['pendingTimer'])
        step(p, 4)
        click(p, 'play')
        p.clock.fast_forward(12001)
        check('Playback stops on the final explanation', state(p)['step'] == 5 and not state(p)['playing'] and not state(p)['pendingTimer'])
        p.locator('[data-select="A"]').click()
        check('Main A distance is visibly derived', '0.424264' in text(p) and '2,200' in text(p))
        p.locator('[data-select="C"]').click()
        check('Main C distance is visibly derived', '方案C的MIDIP=1、HDIP=0.707107' in text(p))
        p.locator('.paper-walkthrough').screenshot(path=str(OUT / 'desktop-distance.png'))
        step(p, 3)
        set_range(p, 'laborCap', 73)
        step(p, 5)
        check('An empty feasible set has no fabricated ideal point', '没有可行方案' in text(p))
        step(p, 3)
        set_range(p, 'laborCap', 74)
        step(p, 5)
        check('A singleton explains its constant columns without NaN', '所有值相同' in text(p) and 'NaN' not in text(p) and 'Infinity' not in text(p))
        step(p, 3)
        set_range(p, 'laborCap', 140)
        step(p, 4)
        check('The inclusive cap boundary lets D enter and dominate', 'F1={D}' in text(p))
        click(p, 'reset')
        p.locator('.rw-side-lessons>summary').click()
        p.locator('.rw-side-join>summary').click()
        p.locator('[data-join="wrong"]').click()
        check('Separate wrong join displays audited 120/36', '收获 120 Mg · 粪肥 36 Mg' in text(p, '.rw-side-join'))
        p.locator('[data-join="correct"]').click()
        check('Separate aggregate-first join displays audited 60/12', '收获 60 Mg · 粪肥 12 Mg' in text(p, '.rw-side-join'))
        p.locator('.rw-side-metrics>summary').click()
        for key, expected in {'gm':'1,900','dey':'45.82','labor':'74','gwd':'260','nl':'83.5','ghg':'2.5','pu':'6 doses/year'}.items():
            p.locator(f'[data-metric="{key}"]').click()
            check(f'Independent {key} example has its audited output', expected in text(p, '.rw-side-metric-result'))
        set_range(p, 'area', 3)
        check('Changing area never multiplies pesticide application count', '仍为6次' in text(p, '.rw-side-metric-result'))
        check('Independent lenses do not mutate main farm inputs', state(p)['values']['costAW'] == 1000 and state(p)['values']['waterAW'] == 300)
        click(p, 'reset')
        p.locator('.rw-side-lessons>summary').click()
        step(p, 5)
        issues = p.evaluate('''()=>{const root=document.querySelector('.paper-walkthrough'),ids=[...document.querySelectorAll('[id]')].map(e=>e.id),issues=[];if(new Set(ids).size!==ids.length)issues.push('duplicate IDs');for(const e of root.querySelectorAll('input,select'))if(!document.querySelector(`label[for="${e.id}"]`))issues.push('unlabelled input');for(const b of root.querySelectorAll('button'))if(!b.textContent.trim()&&!b.getAttribute('aria-label'))issues.push('unnamed button');for(const s of root.querySelectorAll('svg'))if(!s.querySelector('title')||!s.querySelector('desc'))issues.push('missing SVG text');for(const t of root.querySelectorAll('table'))if(!t.caption||!t.querySelector('th[scope=col]'))issues.push('table semantics');return issues;}''')
        check('Unique IDs, semantic tables, labels and SVG alternatives are present', not issues)
        p.evaluate('document.body.classList.add("dark")')
        check('Dark mode inherits existing ink color', p.locator('.paper-walkthrough').evaluate('(el)=>getComputedStyle(el).color') == 'rgb(229, 235, 227)')
        p.locator('.paper-walkthrough').screenshot(path=str(OUT / 'desktop-dark.png'))
        p.evaluate('document.body.classList.remove("dark")')
        click(p, 'reset')
        step(p, 1)
        check('Reading beyond step zero defers an automatic refresh', busy(p))
        click(p, 'play')
        p.evaluate('dispatchEvent(new HashChangeEvent("hashchange"))')
        check('Route change clears ephemeral busy state and all playback timers', not busy(p) and not state(p)['pendingTimer'])
        p.evaluate('document.querySelector("#research-walkthrough").remove()')
        p.wait_for_function('!controller.getState().mounted')
        check('Detaching the panel cleans up its controller', not state(p)['pendingTimer'] and not busy(p))
        p.evaluate('()=>{const s=document.createElement("section");s.id="research-walkthrough";document.querySelector("main").append(s);window.controller=PaperWalkthrough.mount(s)}')
        check('Mount works again after cleanup', p.locator('.paper-walkthrough').count() == 1)
        context.close()
        mobile, mp = boot(browser, is_mobile=True, device_scale_factor=1)
        for width in [360, 320]:
            mp.set_viewport_size({'width': width, 'height': 800})
            for i in range(6):
                step(mp, i)
                check(f'{width}px step {i+1} has no page overflow', mp.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
        step(mp, 3)
        mp.locator('.paper-walkthrough').screenshot(path=str(OUT / 'mobile-feasibility.png'))
        mobile.close()
        reduced, rp = boot(browser, reduced_motion='reduce')
        check('Reduced motion disables playback and states why', rp.locator('[data-action="play"]').is_disabled() and rp.locator('.rw-motion-note').is_visible())
        step(rp, 5)
        check('Reduced motion preserves full manual calculation access', '0.424264' in text(rp))
        check('Reduced motion suppresses CSS animation', rp.locator('[aria-current="step"]>span').evaluate('(el)=>getComputedStyle(el).animationName') == 'none')
        reduced.close()
        check('No JavaScript page errors', not errors)
        check('No external assets or network requests', not requests)
        (OUT / 'browser-report.json').write_text(json.dumps({'passed':checks,'pageErrors':errors,'networkRequests':requests},ensure_ascii=False,indent=2))
        print(json.dumps({'passed':len(checks),'report':str(OUT / 'browser-report.json')}))
    finally:
        browser.close()
