"""Study v3 acceptance tests. Existing suites still run separately, no relaxed assertions."""
from pathlib import Path
from http.server import ThreadingHTTPServer,SimpleHTTPRequestHandler
from functools import partial
import json,threading,hashlib,re
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'dist/site';RES=ROOT/'test-results';RES.mkdir(exist_ok=True)
class Quiet(SimpleHTTPRequestHandler):
 def log_message(self,*args):pass
server=ThreadingHTTPServer(('127.0.0.1',8783),partial(Quiet,directory=str(OUT)));threading.Thread(target=server.serve_forever,daemon=True).start();URL='http://127.0.0.1:8783/';checks=[];errors=[]
framework=json.loads((ROOT/'study/frameworks.json').read_text());papers=json.loads((ROOT/'content/papers.json').read_text());catalog=json.loads((ROOT/'resources/catalog.json').read_text());formulas=json.loads((ROOT/'resources/formulas/index.json').read_text());translations=json.loads((ROOT/'resources/translations/index.json').read_text());release=json.loads((OUT/'release.json').read_text())
assert len(framework['papers'])==len(papers)==21
for p in papers:
 assert sorted(i for g in framework['papers'][p['id']]['stages'] for i in g['details'])==list(range(len(p['sections'])))
checks.append('All 21 research arguments map every existing close-reading section exactly once')
for r in translations['records']:
 t=json.loads((OUT/r['path']).read_text());assert '-nd' not in t['license']['url'];assert t['coverage']['untranslatedTextBlocks']==0
checks.append('All public paragraph files cover source blocks and exclude no-derivatives translations')
liang=next(r for r in formulas['records'] if r['id']=='liang-2022');lf=json.loads((OUT/liang['path']).read_text());assert {e['label'] for e in lf['equations'] if e.get('mathML')}=={'9','10','11','12'},'Missing source-checked core expressions'
checks.append('Liang 2022 equations 9–12 have source-checked mathematical markup and original proof crops')
with sync_playwright() as p:
 browser=p.chromium.launch();c=browser.new_context(viewport={'width':1280,'height':900},accept_downloads=True);page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
 try:
  page.goto(URL+'#/study-map');page.wait_for_selector('.reader');assert '研究框架' in page.locator('h1').inner_text();checks.append('Whole-field framework is a working, searchable reading entry')
  page.goto(URL+'#/liang-2022');page.wait_for_selector('.study-overview');assert page.locator('.study-stage').count()==5;assert page.locator('.method-drilldown').count()==5
  page.goto(URL+'#/liang-2022/s3');page.wait_for_selector('#s3');assert page.locator('#s3').is_visible();assert page.locator('#s3').evaluate("e=>e.closest('details').open");checks.append('Framework first with old detailed sections and legacy deep links preserved')
  term=page.locator('#s3 .term-token[data-term="midip"]').first;term.click();page.wait_for_selector('#term-explainer');assert '整体' in page.locator('#term-explainer').inner_text();page.locator('.articlehead h1').click();page.wait_for_selector('#term-explainer',state='detached');checks.append('Guided-reading term opens locally and tap outside dismisses it')
  page.goto(URL+'#/original/liang-2022');page.wait_for_selector('#bilingual-status');assert int(page.locator('#bilingual-status').get_attribute('data-coverage'))>200
  pair=page.locator('.bilingual-pair:has(.paragraph-zh p)').first;pair.scroll_into_view_if_needed();assert pair.locator('.original-block').inner_text();assert re.search('[\u3400-\u9fff]',pair.locator('.paragraph-zh p').inner_text())
  page.locator('#zh-toggle').click();assert page.locator('#zh-toggle').get_attribute('aria-pressed')=='false';assert not pair.locator('.paragraph-zh').is_visible();page.reload();page.wait_for_selector('#zh-toggle');assert page.locator('#zh-toggle').get_attribute('aria-pressed')=='false';page.locator('#zh-toggle').click();checks.append('Actual Chinese follows original paragraphs; right-side toggle persists across reload')
  tok=page.locator('.original-text .term-token[data-term="positive-deviance"]').first;tok.click();page.wait_for_selector('#term-explainer');assert '正向偏离' in page.locator('#term-explainer').inner_text();page.keyboard.press('Escape');page.wait_for_selector('#term-explainer',state='detached');checks.append('English source terms have contextual Chinese explanation and keyboard dismissal')
  eq=page.locator('.formula-display[data-equation="9"]');eq.scroll_into_view_if_needed();assert eq.locator('math msqrt').count()==1;assert eq.locator('.formula-raw').count()==1;assert not eq.locator('.formula-raw').get_attribute('open');assert eq.locator('.formula-scroll').evaluate('e=>e.scrollHeight<=e.clientHeight+3');page.screenshot(path=str(RES/'study-equations.png'),full_page=False);checks.append('Displayed equation remains a complete math object; raw fragmented extraction is folded, not deleted')
  # Select across nested term spans, proving term markup does not replace the real text layer.
  page.evaluate('''()=>{const els=[...document.querySelectorAll('.bilingual-pair>.original-block')];const e=els.find(e=>e.textContent.length>280&&e.getBoundingClientRect().height>0);e.scrollIntoView();const w=document.createTreeWalker(e,NodeFilter.SHOW_TEXT);let first,last,n,total=0;while(n=w.nextNode()){if(!first)first=n;total+=n.length;last=n;if(total>100)break;}const r=document.createRange();r.setStart(first,0);r.setEnd(last,Math.min(30,last.length));const s=getSelection();s.removeAllRanges();s.addRange(r);document.dispatchEvent(new Event('selectionchange'));}''');page.wait_for_selector('#selection-tools');page.locator('[data-quick="underline"]').click();page.wait_for_selector('mark.underline');page.reload();page.wait_for_selector('mark.underline');checks.append('Native selection through nested terminology still creates persistent source underlines')
  page.locator('#reader-mode').click();page.wait_for_timeout(300);page.locator('#next-page').click();assert page.locator('#original-viewport').evaluate('e=>e.scrollLeft')>0;page.locator('#zh-toggle').click();page.locator('#zh-toggle').click();assert page.locator('#original-viewport').evaluate('e=>e.classList.contains("paged")');checks.append('Bilingual toggle and mathematical content work in paged reading')
  # Synthetic private translation import tests mechanism only; no copyrighted private pack is committed.
  nd=next(r for r in catalog['records'] if r['id']=='cheng-2025');nb=json.loads((ROOT/'resources'/nd['bookPath']).read_text());block=next(x for q in nb['pages'] for x in q['blocks'] if len(x.get('text',''))>180);h=hashlib.sha256(re.sub(r'\s+',' ',re.sub('\u00ad'+r'\s*','',block['text'])).strip().encode()).hexdigest();bundle={'schema':'paper.private.translations.v3','translations':[{'schema':'paper.translations.v3','sourceHash':nb['sourceHash'],'docId':nb['id'],'blocks':{block['id']:{'zh':'仅用于测试的本机中文，非真实论文译文。','sourceTextHash':h,'status':'machine-draft'}}}]}
  page.evaluate('async x=>await PaperStudy.importTranslations(new File([JSON.stringify(x)],"test.json",{type:"application/json"}))',bundle);page.goto(URL+'#/original/cheng-2025');page.wait_for_selector('#bilingual-status');assert '仅用于测试' in page.locator('.paragraph-zh').inner_text();checks.append('Private Chinese pack imports locally and binds to exact original hash')
  page.goto(URL+'#/offline');page.wait_for_selector('#cache-site');page.evaluate('navigator.serviceWorker.ready.then(()=>true)');page.locator('#cache-site').click();page.wait_for_function("document.querySelector('#cache-status').textContent.includes('已完整缓存')",timeout=300000)
  c.set_offline(True);page.goto(URL+'#/original/xu-2024');page.wait_for_selector('#bilingual-status');assert int(page.locator('#bilingual-status').get_attribute('data-coverage'))>100;assert page.locator('.paragraph-zh p').count()>100;page.reload();page.wait_for_selector('#zh-toggle');checks.append('Never-opened original loads real Chinese paragraphs with network disabled')
  page.goto(URL+'#/original/liang-2022');page.wait_for_selector('#bilingual-status');eq=page.locator('.formula-display[data-equation="9"]');eq.scroll_into_view_if_needed();eq.locator('[data-formula-proof]').click();page.wait_for_selector('.formula-proof-dialog img');page.wait_for_function("document.querySelector('.formula-proof-dialog img').naturalWidth>0");page.locator('.formula-proof-dialog button').click();checks.append('Original equation proof images are fully cached, not external links')
  page.goto(URL+'#/liang-2023');page.wait_for_selector('.study-overview');assert page.locator('.study-stage').count()==5;checks.append('New coherent guided-reading framework also works fully offline');c.set_offline(False)
  phone=browser.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,device_scale_factor=2);m=phone.new_page();m.on('pageerror',lambda e:errors.append(str(e)));m.goto(URL+'#/original/liang-2022');m.wait_for_selector('#zh-toggle');assert m.evaluate('document.documentElement.scrollWidth<=innerWidth+1');box=m.locator('#zh-toggle').bounding_box();assert box['x']>330 and box['x']+box['width']<=390
  m.locator('.bilingual-pair:has(.paragraph-zh p)').first.scroll_into_view_if_needed();m.screenshot(path=str(RES/'study-mobile-bilingual.png'),full_page=False)
  tok=m.locator('.original-text .term-token[data-term="positive-deviance"]').first;tok.tap();m.wait_for_selector('#term-explainer');rect=m.locator('#term-explainer').bounding_box();assert rect['x']>=0 and rect['x']+rect['width']<=391;assert rect['y']>=0 and rect['y']+rect['height']<=845;m.locator('#zh-toggle').tap();m.wait_for_selector('#term-explainer',state='detached');m.locator('#zh-toggle').tap();m.locator('#reader-mode').tap();m.wait_for_timeout(350);assert m.evaluate('document.documentElement.scrollWidth<=innerWidth+1');checks.append('390px mobile right-side controls, bounded terminology cards and no viewport overflow')
  m.goto(URL+'#/liang-2022');m.wait_for_selector('.study-overview');m.screenshot(path=str(RES/'study-mobile-framework.png'),full_page=False)
  assert not errors,errors
 finally:
  (RES/'study-report.json').write_text(json.dumps({'release':release,'passed':checks,'browserErrors':errors,'limits':['Chromium desktop and mobile simulation, not physical phone testing','Chinese is explicitly marked machine draft unless paragraph manually checked','Private source translations are not publicly distributed']},ensure_ascii=False,indent=2));browser.close();server.shutdown()
print(json.dumps({'passed':checks,'errors':errors},ensure_ascii=False))
