#!/usr/bin/env python3
"""Synthetic browser acceptance for research-reader v5.3; no real user data or credentials."""
from pathlib import Path
from http.server import ThreadingHTTPServer,SimpleHTTPRequestHandler
from threading import Thread
import functools,json,hashlib,time
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'dist/site';RESULTS=ROOT/'test-results';RESULTS.mkdir(exist_ok=True)
class Quiet(SimpleHTTPRequestHandler):
 def log_message(self,*args):pass
server=ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Quiet,directory=str(OUT)))
Thread(target=server.serve_forever,daemon=True).start();BASE=f'http://127.0.0.1:{server.server_port}/'
checks=[];errors=[]
def check(name,ok=True):
 assert ok,name
 checks.append({'name':name,'passed':True})
def goto(page,id):
 page.goto(BASE+'#/'+id) if not page.url.startswith(BASE) else page.evaluate('(id)=>location.hash="#/"+id',id)
 page.wait_for_selector('#view .reader[data-research-v53]',timeout=90000)
 page.wait_for_function('(id)=>location.hash.startsWith("#/"+id)&&document.querySelector("#view .reader")?.dataset.researchV53',id)
 page.wait_for_timeout(250)
try:
 release=json.loads((OUT/'release.json').read_text());research=json.loads((ROOT/'resources/research-v53.json').read_text());documents=json.loads((OUT/'data.json').read_text())['documents'];ids={d['id'] for d in documents}
 check('New research studio, complete indicator audit and sampling method family pages are built',{'research-studio','liang-indicator-audit','sampling-library','sample-size-design','research-decisions','research-feedback'}<=ids)
 check('Seven unique indicator definitions and 32 sampling/design cards',len(research['indicatorRows'])==7 and len({r['id'] for r in research['indicatorRows']})==7 and len(research['samplingCards'])==32)
 check('Every scholarly reading entry has an explicit research lens',all(d['id'] in research['papers'] for d in documents if d['type'] in ['paper','thesis']))
 cat=json.loads((ROOT/'resources/catalog.json').read_text());source=next(r for r in cat['records'] if r['id']=='liang-2022');book=json.loads((OUT/source['bookPath']).read_text());check('Original PDF hash and exact original block strings unchanged',hashlib.sha256((OUT/source['originalPath']).read_bytes()).hexdigest()==source['sha256'] and book==json.loads((ROOT/'resources'/source['bookPath']).read_text()))
 with sync_playwright() as p:
  browser=p.chromium.launch();context=browser.new_context(viewport={'width':1360,'height':900});page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
  goto(page,'liang-indicator-audit');check('Seven indicator rows are present',page.locator('[data-indicator]').count()==7)
  row=page.locator('[data-indicator="labour"]');row.locator(':scope > summary').click();row.locator('.research-evidence > summary').click();page.wait_for_selector('[data-indicator="labour"] .research-excerpt',timeout=45000)
  text=row.inner_text();check('Exact author wording about shared labour coefficients appears beside explanation','could not recall' in text and 'Table S3' in text)
  row.locator('.evidence-page > summary').first.click();image=row.locator('.research-source-figure img').first;image.wait_for();page.wait_for_function('()=>[...document.querySelectorAll("[data-indicator=labour] .research-source-figure img")].some(x=>x.naturalWidth>0)',timeout=45000);check('Complete original page image loads next to relevant metric')
  note=row.locator(':scope > .research-note-box');note.locator('summary').click();note.locator('textarea').fill('SYNTHETIC: explain labour coefficient and seasonal peak');page.wait_for_function('()=>JSON.parse(localStorage.getItem("paper-lab-learning-v1")).notes["research::liang-indicator-audit::indicator-labour"].includes("SYNTHETIC")');goto(page,'sampling-library');page.reload();page.wait_for_selector('.sampling-cards',timeout=60000);check('Immediate per-indicator input survives rapid navigation and refresh',page.evaluate('()=>JSON.parse(localStorage.getItem("paper-lab-learning-v1")).notes["research::liang-indicator-audit::indicator-labour"]')=='SYNTHETIC: explain labour coefficient and seasonal peak')
  check('All method cards appear',page.locator('.sampling-card').count()==32);page.get_by_label('检索样本选取方法').fill('cLHS');check('Method cards searchable without deleting other methods',page.locator('.sampling-card').count()==1);page.get_by_label('检索样本选取方法').fill('')
  goto(page,'liang-2022');page.locator('.research-bridge > .research-evidence > summary').first.click();page.wait_for_selector('.research-bridge .research-excerpt',timeout=30000);a=page.locator('.research-bridge .research-excerpt > a').first;a.click();page.wait_for_selector('#original-text',timeout=45000);page.locator('#back').click();page.wait_for_selector('#view .reader[data-research-v53]',timeout=45000);check('Original-evidence navigation returns to guided reading',page.url.endswith('#/liang-2022'))
  goto(page,'research-studio');box=page.locator('#s0 > .research-section-tools > .research-note-box');box.locator('summary').click();box.locator('textarea').fill('SYNTHETIC-BASE');other=context.new_page();goto(other,'research-studio');ob=other.locator('#s0 > .research-section-tools > .research-note-box');ob.locator('textarea').focus();box.locator('textarea').fill('SYNTHETIC-TAB-A');ob.locator('textarea').fill('SYNTHETIC-TAB-B');merged=other.evaluate('()=>JSON.parse(localStorage.getItem("paper-lab-learning-v1")).notes["research::research-studio::s0"]');check('Concurrent same-box edits retain both versions','TAB-A' in merged and 'TAB-B' in merged);other.close()
  # Seed only explicit synthetic writing into existing stores.
  page.evaluate('''async()=>{for(const [dbName,store,value] of [['paper-workspace-v4','workbooks',{id:'test-workbook',values:{question:'SYNTHETIC-WORKBOOK'},updatedAt:new Date().toISOString()}],['paper-lab-reader-v2','annotations',{id:'test-note',docId:'lesson:liang-2022',segments:[],quote:'SYNTHETIC-QUOTE',comment:'SYNTHETIC-ANNOTATION',tags:[]}],['paper-workspace-v4','terms',{id:'custom-test',zh:'测试术语',en:'test',aliases:['test'],definition:'SYNTHETIC-TERM'}],['paper-comfort-v5','tags',{id:'test-tag',label:'测试',text:'SYNTHETIC-TAG',href:''}],['paper-comfort-v5','drafts',{id:'test-draft',comment:'SYNTHETIC-DRAFT'}],['paper-translations-v3','translations',{id:'test-trans',docId:'liang-2022',block:'test',text:'SYNTHETIC-REVIEWED',reviewed:true}]] ){await new Promise((ok,no)=>{const q=indexedDB.open(dbName,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(store))q.result.createObjectStore(store,{keyPath:'id'});};q.onerror=()=>no(q.error);q.onsuccess=()=>{const d=q.result,t=d.transaction(store,'readwrite');t.objectStore(store).put(value);t.oncomplete=()=>{d.close();ok();};t.onerror=()=>no(t.error);};});}}''')
  goto(page,'research-feedback');page.wait_for_function('()=>document.querySelector(".research-input-status")?.textContent.includes("可读取")');review=page.locator('.research-input-list').inner_text();check('All manual writing surfaces have a consolidated review path',all(x in review for x in ['阅读工作表','自定义术语','自定义标签','草稿','个人校订译文','研究小框','划线']))
  projection=page.evaluate('''async()=>{const x=await PaperSync.capture(),p=PaperReview.project(x.entries);const ignored=PaperReview.project({'["paper-lab-reader-v2","books","private"]':{hash:'x',value:{text:'DO-NOT-EXPORT-SOURCE'}}});return {p,ignored,redaction:PaperReview.redact('ghp_'+'x'.repeat(36)),chunks:PaperReview.chunks(p).length};}''');check('Private assistant projection covers notes without raw books or tokens',all(x in json.dumps(projection['p'],ensure_ascii=False) for x in ['SYNTHETIC-WORKBOOK','SYNTHETIC-ANNOTATION','SYNTHETIC-TERM','SYNTHETIC-TAG','SYNTHETIC-DRAFT','SYNTHETIC-REVIEWED']) and not projection['ignored']['records'] and 'ghp_' not in projection['redaction'])
  check('Local-only notes never claim managed automatic sign-in',page.evaluate('()=>PaperSync.status().connected') is False and release['researchStudio']['automaticSignIn'] is False)
  goto(page,'liang-indicator-audit');page.evaluate('''async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(ok=>navigator.serviceWorker.addEventListener('controllerchange',ok,{once:true}));return new Promise((ok,no)=>{const ch=new MessageChannel();const t=setTimeout(()=>no(Error('cache timeout')),120000);ch.port1.onmessage=e=>{if(e.data.type==='DONE'){clearTimeout(t);e.data.failed.length?no(Error('cache failure')):ok(e.data);}};navigator.serviceWorker.controller.postMessage({type:'CACHE_BOOK',id:'liang-2022'},[ch.port2]);});}''')
  context.set_offline(True);page.reload();page.wait_for_selector('[data-indicator="gwd"]',timeout=45000);row=page.locator('[data-indicator="gwd"]');row.locator(':scope > summary').click();row.locator('.research-evidence > summary').click();page.wait_for_selector('[data-indicator="gwd"] .research-excerpt',timeout=30000);check('New inline evidence works after real network disconnection','0.2' in row.inner_text());row.locator('.evidence-page > summary').first.click();page.wait_for_function('()=>[...document.querySelectorAll("[data-indicator=gwd] .research-source-figure img")].some(x=>x.naturalWidth>0)',timeout=30000);check('Original formula/page image also works offline')
  context.set_offline(False);page.set_viewport_size({'width':390,'height':844});goto(page,'sampling-library');check('Sampling topic fits 390px viewport',page.evaluate('()=>document.documentElement.scrollWidth<=innerWidth+2'));page.screenshot(path=str(RESULTS/'research-v53-mobile.png'),full_page=False)
  goto(page,'liang-indicator-audit');page.locator('[data-indicator="gm"] > summary').click();check('Indicator explanation and note controls fit mobile width',page.evaluate('()=>document.documentElement.scrollWidth<=innerWidth+2'));page.screenshot(path=str(RESULTS/'research-v53-indicators.png'),full_page=False)
  # Imported source text is not mutated by adding the research layer.
  page.set_viewport_size({'width':1280,'height':900});page.evaluate('()=>location.hash="#/original/liang-2022/p4-b7-d793468"');page.wait_for_selector('#p4-b7-d793468',timeout=45000);text=page.locator('#p4-b7-d793468').inner_text();check('Research layer leaves exact original paragraph words unchanged','sustainability indicators were selected accounting for local challenges' in ' '.join(text.split()))
  check('No uncaught application errors in research-reader acceptance',not errors);browser.close()
 report={'schema':'paper.research.acceptance.v53','passed':True,'appVersion':release['appVersion'],'contentVersion':release['version'],'checks':checks,'browser':'Chromium desktop + 390px viewport; not a physical phone','scope':'Synthetic local records and existing private-sync interfaces. No provided PAT tested and no managed backend deployed. Exact source paragraph anchors tested; not a visual audit of all original figures.','errors':errors}
 (RESULTS/'research-v53-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(json.dumps({'passed':True,'checks':len(checks)}))
except Exception as e:
 (RESULTS/'research-v53-report.json').write_text(json.dumps({'passed':False,'checks':checks,'error':str(e),'errors':errors},ensure_ascii=False,indent=2));raise
finally:server.shutdown()
