/* Paper Lab: no CDN, no server-side user data, no browser credentials. */
(() => {
'use strict';
const D=window.PAPER_DATA, docs=D.documents, byId=new Map(docs.map(d=>[d.id,d]));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:'#';}catch{return '#';}};
const KEY='paper-lab-learning-v1'; let store={},blocked=false;
try{store=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{blocked=true;}
if(!store||typeof store!=='object'||Array.isArray(store))store={};
for(const k of ['notes','done','positions','sourcePageX'])if(!store[k]||typeof store[k]!=='object')store[k]={};
let route='', toastTimer, restoreLock=false, registration, installEvent, pendingSourcePaper=null, sourceSelection=null;\nconst SR=()=>window.PaperSourceReader;
const toast=m=>{const t=$('#toast');t.textContent=m;t.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.style.display='none',4200);};
function persist(){try{localStorage.setItem(KEY,JSON.stringify(store));return true;}catch{blocked=true;return false;}}
function rich(s){return String(s||'').split(/\n\n/).map(p=>'<p>'+esc(p).replace(/\[\[([a-z0-9-]+)\|([^\]]+)\]\]/g,(_,id,label)=>`<a href="#/${id}">${label}</a>`).replace(/(https:\/\/[^\s<，。；]+)/g,u=>`<a href="${esc(safeUrl(u))}" target="_blank" rel="noopener noreferrer">${u}</a>`)+'</p>').join('');}
function link(id,label){return `<a href="#/${esc(id)}">${esc(label||byId.get(id)?.title||id)}</a>`;}
function cards(arr){return `<div class="grid">${arr.map(d=>`<article class="card"><span class="label">${esc(d.stage||d.type)}${d.year?' · '+d.year:''}</span><h3>${link(d.id,d.title)}</h3><div class="meta">${esc(d.author||'方法与实践')} · 约${d.minutes||15}分钟${store.done[d.id]?' · 已完成自测':''}</div><p>${esc(d.summary)}</p><div class="tags">${(d.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article>`).join('')}</div>`;}
function head(title,sub){return `<header class="pagehead"><span class="eyebrow">PAPER LAB / LEARN BY DOING</span><h1>${esc(title)}</h1><p>${esc(sub||'')}</p></header>`;}
function download(name,text,mime='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([text],{type:mime})),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function savePosition(){if(restoreLock)return;const s=history.state||{};history.replaceState({...s,pl:true,y:scrollY},'',location.href);const id=route.split('/')[0];if(byId.has(id)){store.positions[id]={route:location.hash,y:scrollY,at:Date.now()};store.last=id;persist();}}
function go(hash,{restore=false}={}){savePosition();const pos=restore?store.positions[hash.replace(/^#\//,'').split('/')[0]]:null;history.pushState({pl:true,y:pos?.y||0},'',pos?.route||hash);render(!!pos);}
function home(){const papers=docs.filter(d=>['paper','thesis'].includes(d.type)),methods=docs.filter(d=>d.type==='method');return `<section class="hero"><span class="eyebrow">FARMING SYSTEMS · GUIDED READING</span><h1>不只是读过论文。<br>要能解释，也能亲手做。</h1><p class="lead">沿着真实农场、规则生成、时空规划和利益相关者这条线，理解农业系统研究。每个概念都能跳转，每次阅读都能接着继续。</p><div class="actions"><a class="btn" href="#/liang-2022">开始第一课 →</a><a class="btn secondary" href="#/course">查看完整学习路线</a><a class="btn secondary" href="#/offline">保存到手机</a></div><div class="stats"><div class="stat"><strong>${papers.length}</strong><span>论文 / 学位论文学习条目</span></div><div class="stat"><strong>${methods.length}</strong><span>理论与方法专题</span></div><div class="stat"><strong>7</strong><span>循序渐进学习单元</span></div><div class="stat"><strong>${Object.values(store.done).filter(Boolean).length}</strong><span>本机已完成自测</span></div></div></section><div class="sectionhead"><h2>先看全局，再进入一篇</h2>${link('model-map','查看模型关系 →')}</div><div class="flow">${[['01','现实系统','liang-2022','调查、指标、正向案例'],['02','方案生成','liang-2023','ROTAT、Pareto、方案分类'],['03','时空规划','farmsteps-2026','地块、时间、农场约束'],['04','人的选择','cheng-2025','感知、Q排序、景观设计']].map(([n,t,id,s])=>`<a href="#/${id}"><b>${n}</b><strong>${t}</strong><small>${s}</small></a>`).join('')}</div><div class="sectionhead"><h2>优先带读</h2><a href="#/library">全部文库 →</a></div>${cards(['liang-2022','liang-2023','farmsteps-2026','cheng-2023','cheng-2025','xu-2024'].map(id=>byId.get(id)))}<div class="notice">论文页明确标注核读范围。三本博士论文目前是官方摘要和相关文章导航，不假装已经逐章精读；教学数据也不冒充作者原始数据。${link('corrections','查看核验记录 →')}</div>`;}
function library(type){const arr=docs.filter(d=>type==='methods'?d.type==='method':['paper','thesis'].includes(d.type));return head(type==='methods'?'方法工具箱':'论文文库',type==='methods'?'从定义、手算到最小练习。每个方法都能回到使用它的论文。':'优先梁政渊与程嘉莉，串联徐展及全农场、景观、养分和风险方法。')+`<div class="filters"><button data-filter="all" class="active">全部</button>${(type==='methods'?['基础','建模','调查','数据']:['梁政渊','程嘉莉','徐展','博士','模型']).map(x=>`<button data-filter="${x}">${x}</button>`).join('')}</div><div id="catalog">${cards(arr)}</div>`;}
function article(d){const toc=d.sections.map((s,i)=>`<a href="#/${d.id}/s${i}">${i+1}. ${esc(s[0])}</a>`).join('');return `<div class="reader-layout"><article class="reader"><header class="articlehead"><span class="eyebrow">${esc(d.stage||'GUIDED READING')}${d.year?' / '+d.year:''}</span><h1>${esc(d.title)}</h1>${d.en?`<div class="english">${esc(d.en)}</div>`:''}<p class="citation">${esc(d.citation||'原创教学讲解；文献依据见本页来源')}</p><p class="summary">${esc(d.summary)}</p>${d.evidence?`<div class="notice">核读范围：${esc(d.evidence)}</div>`:''}<div class="source-links"><a href="#/source/${d.id}">站内原文阅读 / 划线批注</a>${[['url','在线来源（需网络）'],['dataUrl','作者数据入口（需网络）']].filter(([k])=>d[k]).map(([k,t])=>`<a href="${esc(safeUrl(d[k]))}" target="_blank" rel="noopener noreferrer">${t} ↗</a>`).join('')}${d.pdf?`<a href="${esc(safeUrl(d.pdf))}" target="_blank" rel="noopener noreferrer">原PDF来源（需网络） ↗</a>`:''}<a href="read/${d.id}.html">静态带读版</a></div><div class="articletools"><span>约${d.minutes||20}分钟 · ${d.sections.length}节</span><button data-font="-1" aria-label="缩小文字">A−</button><button data-font="1" aria-label="放大文字">A+</button><button id="print">打印 / 存为PDF</button></div></header><details class="mobiletoc"><summary>本篇目录</summary>${toc}</details>${d.sections.map((s,i)=>`<section id="s${i}"><span class="kind">${esc(s[1])}</span><h2>${i+1}. ${esc(s[0])}</h2><div class="prose">${s[1]==='教学代码'?`<pre><code>${esc(s[2])}</code></pre>`:rich(s[2])}</div>${s[3]?`<div class="source-note">出处 / 范围：${esc(s[3])}${d.url?` · <a href="#/source/${d.id}">站内原文 / 批注 →</a>`:''}</div>`:''}</section>`).join('')}${d.sources?.length?`<section><h2>方法依据与应用论文</h2>${d.sources.map(id=>`<p>${link(id)}</p>`).join('')}</section>`:''}${d.quiz?.length?`<section id="self-test"><span class="kind">自测</span><h2>合上原文，试着回答</h2>${d.quiz.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}<label class="donecontrol"><input id="done" type="checkbox" ${store.done[d.id]?'checked':''}>我已经尝试回答并核对，标记本篇完成（不是只读到页尾）。</label></section>`:''}<section><h2>我的笔记</h2><textarea id="note" class="notearea" aria-label="本篇阅读笔记" placeholder="写下你的理解、疑问和复现结果。仅保存本机，建议定期导出。">${esc(store.notes[d.id]||'')}</textarea><div id="note-status" class="notestatus">${blocked?'本地存储不可用；请导出备份。':'本机保存；不会上传GitHub或发送给第三方。'}</div><button data-action="export">导出全部笔记与进度</button></section>${d.related?.length?`<section><h2>继续连接</h2><div class="source-links">${d.related.map(id=>link(id)).join('')}</div></section>`:''}</article><aside class="toc"><strong>IN THIS READING</strong>${toc}${d.quiz?.length?`<a href="#/${d.id}/self-test">自测与笔记</a>`:''}<p>${link('course','← 返回全局路线')}</p></aside></div>`;}
function searchPage(query){const q=query.trim().toLowerCase();const hits=q?docs.filter(d=>JSON.stringify(d).toLowerCase().includes(q)):[];return head('全站搜索',q?`“${query}” · ${hits.length}条结果；搜索包含全文、作者、术语和自测。`:'输入论文名、作者或卡住的概念。')+(hits.length?cards(hits):'<div class="empty">没有匹配项。可尝试 Pareto、梁政渊、Q方法、劳动力等词。</div>');}
function notes(){const list=docs.filter(d=>store.notes[d.id]||store.done[d.id]);return head('我的笔记与进度','数据仅保存在此浏览器；导出后可备份或导入其他设备。同一浏览器同一域名的两站使用同一学习数据键。')+`<div class="actions"><a class="btn" href="#/annotations">打开划线与便签管理</a><a class="btn secondary" href="#/sources">原文书库</a><button data-action="export">导出JSON备份</button><button data-action="import">导入合并（不清空现有）</button></div>`+(list.length?list.map(d=>`<article class="card"><h3>${link(d.id)}</h3><small>${store.done[d.id]?'已完成自测':'阅读中'}</small><div class="prose">${rich((store.notes[d.id]||'未填写笔记').slice(0,1500))}</div></article>`).join(''):'<div class="empty">从第一篇开始。阅读位置会自动记录，笔记与自测由你主动填写。</div>');}
function offline(){return head('离线与下载','完整网站会缓存原文阅读器与PDF解析模块；你导入原文书库的文件存于本设备IndexedDB，之后可断网阅读。公开站不会擅自镜像受版权限制的整篇论文或第三方网站。')+`<section class="card"><h2>01 · 保存网站到这台手机</h2><p>正文、搜索、方法、原文阅读器、划线便签和PDF解析模块一起保存。已导入的论文原文件与提取文字本来就在本机，可离线继续阅读；浏览器仍可能清理站点数据，请保留原PDF并导出重要笔记。</p><p><a href="#/sources">管理本机原文书库 →</a> · <a href="#/annotations">管理划线与便签 →</a></p><div class="actions"><button class="primary" id="cache-site">缓存完整网站</button><button id="check-cache">检查离线状态</button><button id="check-update">检查新版本</button><button id="install-app">安装 / 添加到主屏幕</button></div><p id="cache-status" role="status">${location.protocol==='file:'?'当前为本地单文件：正文和教学无需联网。':'等待检查缓存状态。'}</p></section><section class="card"><h2>02 · 下载独立备份</h2><p>单文件HTML无需服务器和第三方资源。手机系统若仅显示文件预览，请优先使用已缓存的网站或添加到主屏幕。</p><div class="actions"><a class="btn" href="downloads/Paper-Lab-offline.html" download>离线单文件HTML</a><a class="btn secondary" href="downloads/Paper-Lab-offline.zip" download>完整网站与练习ZIP</a><button data-action="export">学习笔记JSON</button></div><p><a href="#/offline-help">完整使用说明 →</a></p></section><section class="card"><h2>03 · 教学数据与可运行脚本</h2><p>所有数据均为明确标记的自编教学示例，不能用来重现作者原始样本数量与论文结果。</p><div class="downloadlist">${Object.keys(D.files||{}).map(name=>`<button data-file="${esc(name)}">${esc(name)}<small>从当前页面内嵌数据下载，已缓存或单文件状态下也可使用。</small></button>`).join('')}</div></section>`;}
let farmRows=[['A',100,30,80],['B',80,40,100],['C',120,50,90],['D',90,20,70],['E',100,30,80],['F',110,35,120]];
function lab(){return head('交互实验室','自编小数据。先猜结果，再改变条件，最后用代码验证。不是作者原始数据，也不是农业处方。')+`<section class="card"><h2>实验1 · 手动改变Pareto前沿</h2><p>利润提高，用水和劳动减少。点击目标开关，比较前沿如何变化。数值均为无实际单位的教学分数。</p><div class="labcontrols"><label><input class="objective" type="checkbox" value="1" checked>利润 ↑</label><label><input class="objective" type="checkbox" value="2" checked>用水 ↓</label><label><input class="objective" type="checkbox" value="3" checked>劳动 ↓</label></div><div class="tablewrap"><table class="labtable"><thead><tr><th>方案</th><th>利润</th><th>用水</th><th>劳动</th><th>结果</th></tr></thead><tbody>${farmRows.map((r,i)=>`<tr><td>${r[0]}</td>${r.slice(1).map((v,j)=>`<td><input type="number" value="${v}" step="1" data-farm="${i}" data-col="${j+1}" aria-label="方案${r[0]}指标${j+1}"></td>`).join('')}<td id="result-${i}"></td></tr>`).join('')}</tbody></table></div><p id="pareto-result" role="status"></p><svg id="pareto-plot" class="labplot" viewBox="0 0 640 300" role="img" aria-label="利润与用水二维投影；筛选依据所勾选目标"></svg><p><small>二维图只画利润和水，不代表劳动目标不存在。完全重复方案不会互相严格支配。</small></p><a href="#/pareto">返回定义 →</a></section><section class="card"><h2>实验2 · 20张卡片，不能全部选最重要</h2><p>用自编陈述体验Q-sort，五档位置必须为2–4–8–4–2。它不是程嘉莉原问卷，也不会产生有效科学观点分类。</p><div class="qgrid" id="q-counts"></div><div class="qchoices">${['稳定收入','减少用水','更多食物','减少氮损失','减少工作时长','保留景观','土壤肥力','减少化学投入','低投资成本','家庭时间','生物多样性','风险缓冲','学习机会','文化传统','非农机会','产品品质','易于管理','市场稳定','资源循环','未来灵活性'].map((t,i)=>`<label class="qrow">${i+1}. ${t}<select class="q-select" aria-label="${t}排序"><option value="">未选</option>${[1,2,3,4,5].map(n=>`<option value="${n}">${n}分</option>`).join('')}</select></label>`).join('')}</div><p id="q-result" role="status"></p><button id="export-q">导出这次教学排序</button><p><a href="#/q-method">Q-sort如何成为典型观点？ →</a></p></section>`;}
function updatePareto(){const cols=$$('.objective:checked').map(n=>Number(n.value));let valid=farmRows.every(r=>r.slice(1).every(Number.isFinite));if(!valid||!cols.length){$('#pareto-result').textContent='请填写全部有限数值，并至少选择一个目标。';return;}const cost=r=>cols.map(k=>r[k]*(k===1?-1:1));const nd=farmRows.map((r,i)=>!farmRows.some((s,j)=>j!==i&&cost(s).every((v,k)=>v<=cost(r)[k])&&cost(s).some((v,k)=>v<cost(r)[k])));farmRows.forEach((r,i)=>{$('#result-'+i).textContent=nd[i]?'非支配':'被支配';$('#result-'+i).className=nd[i]?'good':'bad';});$('#pareto-result').textContent='当前非支配方案：'+farmRows.filter((_,i)=>nd[i]).map(r=>r[0]).join('、');const xs=farmRows.map(r=>r[1]),ys=farmRows.map(r=>r[2]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);const px=v=>55+(v-xmin)/(xmax-xmin||1)*520,py=v=>245-(v-ymin)/(ymax-ymin||1)*195;$('#pareto-plot').innerHTML=`<path d="M45 30V255H605" stroke="currentColor" fill="none"/><text x="510" y="285" fill="currentColor" font-size="13">利润 ↑</text><text x="8" y="20" fill="currentColor" font-size="13">用水</text>${farmRows.map((r,i)=>`<circle cx="${px(r[1])}" cy="${py(r[2])}" r="${nd[i]?7:5}" fill="${nd[i]?'var(--accent)':'var(--muted)'}" opacity=".7"/><text x="${px(r[1])+9}" y="${py(r[2])-8+i%2*20}" font-size="13" fill="currentColor">${r[0]}</text>`).join('')}`;}
function updateQ(){const values=$$('.q-select').map(s=>Number(s.value)),counts=[1,2,3,4,5].map(n=>values.filter(v=>v===n).length),cap=[2,4,8,4,2];$('#q-counts').innerHTML=counts.map((n,i)=>`<div class="qcol"><span>${i+1}分</span><strong>${n} / ${cap[i]}</strong></div>`).join('');const ok=counts.every((n,i)=>n===cap[i]);$('#q-result').textContent=ok?'排序符合网格。请进一步解释两端卡片的选择理由；这不是观点因子分析。':'请调整到2–4–8–4–2；未完成'+values.filter(v=>v===0).length+'张。';}
async function cacheStatus(){const el=$('#cache-status');if(!el)return;if(!('serviceWorker' in navigator)||location.protocol==='file:'){el.textContent='本地单文件无需缓存；服务工作线程仅适用于HTTPS或localhost。';return;}try{registration=await navigator.serviceWorker.ready;const worker=registration.active;if(!worker)throw Error('服务工作线程尚未激活');const result=await new Promise((resolve,reject)=>{const ch=new MessageChannel();const timer=setTimeout(()=>reject(Error('缓存状态检查超时')),12000);ch.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data);};worker.postMessage({type:'STATUS'},[ch.port2]);});el.textContent=result.complete?`已完整缓存 ${result.count} 个本站资源，可测试断网刷新。版本 ${result.version}。外部论文不在其中。`:`缓存不完整（${result.count}/${result.expected}）。请联网后重试。`; }catch(e){el.textContent='未确认缓存完成：'+e.message;}}
function bind(){const d=byId.get(route.split('/')[0]);if($('#note'))$('#note').oninput=e=>{store.notes[d.id]=e.target.value;$('#note-status').textContent=persist()?'已保存到本设备。':'保存失败，请立即导出笔记备份。';};if($('#done'))$('#done').onchange=e=>{store.done[d.id]=e.target.checked;persist();};if($('#print'))$('#print').onclick=()=>window.print();$$('[data-font]').forEach(b=>b.onclick=()=>{store.font=Math.min(23,Math.max(15,(store.font||17)+Number(b.dataset.font)));document.documentElement.style.setProperty('--body-size',store.font+'px');persist();});$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));const type=route==='methods'?'method':'paper';let arr=docs.filter(d=>type==='method'?d.type==='method':['paper','thesis'].includes(d.type));const f=b.dataset.filter;if(f!=='all')arr=arr.filter(d=>JSON.stringify(d).includes(f)||(f==='博士'&&d.type==='thesis'));$('#catalog').innerHTML=cards(arr);});$$('[data-action="export"]').forEach(b=>b.onclick=()=>download('Paper-Lab-notes.json',JSON.stringify({schema:'paper-lab-learning-v1',exportedAt:new Date().toISOString(),data:store},null,2),'application/json'));$$('[data-action="import"]').forEach(b=>b.onclick=()=>$('#import-file').click());$$('[data-file]').forEach(b=>b.onclick=()=>download(b.dataset.file,D.files[b.dataset.file]));if($('#cache-site'))$('#cache-site').onclick=async()=>{if(location.protocol==='file:'){toast('当前单文件已可离线阅读。');return;}$('#cache-status').textContent='正在准备，请保持网络连接…';try{if(navigator.storage?.persist)await navigator.storage.persist();await navigator.serviceWorker.ready;await cacheStatus();}catch(e){$('#cache-status').textContent='缓存失败：'+e.message;}};if($('#check-cache'))$('#check-cache').onclick=cacheStatus;if($('#check-update'))$('#check-update').onclick=async()=>{try{const r=registration||await navigator.serviceWorker.getRegistration();if(!r){toast('当前环境不支持在线更新；请下载新离线文件。');return;}await r.update();toast(r.waiting?'发现新版本，请使用底部更新按钮。':'已检查。内容发布后会检测到新版本。');}catch{toast('暂时无法连接，请保留现有离线内容。');}};if($('#install-app'))$('#install-app').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null;}else toast('Android使用浏览器“安装应用/添加到主屏幕”；iPhone使用Safari分享菜单“添加到主屏幕”。');};if(route==='lab'){updatePareto();updateQ();$$('.objective').forEach(e=>e.onchange=updatePareto);$$('[data-farm]').forEach(e=>e.oninput=()=>{farmRows[+e.dataset.farm][+e.dataset.col]=e.value.trim()===''?NaN:Number(e.value);updatePareto();});$$('.q-select').forEach(e=>e.onchange=updateQ);$('#export-q').onclick=()=>download('teaching-qsort.json',JSON.stringify({label:'SYNTHETIC TEACHING EXERCISE; NOT RESEARCH DATA',scores:$$('.q-select').map(e=>Number(e.value)||null)},null,2),'application/json');}}

function sourceShell(paperId,anchor){
  const d=byId.get(paperId);if(!d||!['paper','thesis'].includes(d.type))return head('没有找到论文','请从论文文库进入。');
  return head('站内原文 · '+d.title,'像小说一样连续阅读，也可切换横向翻页。完整原文件仅保存在本设备；站内不会把受版权限制的全文上传到公开仓库。')+`<section class="source-reader-card"><div class="source-reader-head"><div><span class="kind">LOCAL ORIGINAL</span><h2>${esc(d.en||d.title)}</h2><p id="source-local-status">正在检查本机原文…</p></div><div class="actions"><button data-source-import="${esc(d.id)}">导入/替换原文</button><a class="btn secondary" href="#/${esc(d.id)}">返回带读</a><a class="btn secondary" href="#/annotations">便签管理</a></div></div><div id="source-controls" class="source-controls hidden"><button id="source-mode-scroll">上下滑动</button><button id="source-mode-page">翻页模式</button><button id="source-prev">← 上一屏</button><button id="source-next">下一屏 →</button><button id="source-share">分享到WPS/外部阅读器</button><button id="source-download">保存原文件</button></div><div id="source-reader-body" data-paper="${esc(d.id)}" data-anchor="${esc(anchor||'')}"></div><div id="selection-tools" class="selection-tools" hidden><span>已选择文字</span><button data-ann-kind="highlight">高亮</button><button data-ann-kind="focus">重点</button><button data-ann-kind="underline">下划线</button><button data-ann-kind="note">留便签</button><button data-ann-cancel>取消</button></div></section>`;
}
function sourcesShell(){
  const arr=docs.filter(d=>['paper','thesis'].includes(d.type));
  return head('原文书库','主入口不再直接把你扔到PDF。每篇论文都有站内原文入口；可导入你合法持有的PDF/HTML/TXT/Markdown，原文件和提取文字仅存在本设备。')+`<div class="notice warn">第三方网页与论文存在版权、登录和动态脚本边界。公开仓库只长期保存本站原创带读、书目信息和链接状态；完整受限原文请本机导入。这样既能断网阅读，也不会把私人/受限副本公开发布。</div><div id="source-library" class="grid">${arr.map(d=>`<article class="card" data-source-card="${esc(d.id)}"><span class="label">${esc(d.author||'')} · ${esc(d.year||'')}</span><h3><a href="#/source/${esc(d.id)}">${esc(d.title)}</a></h3><p data-source-status>检查本机副本…</p><div class="actions"><a class="btn" href="#/source/${esc(d.id)}">站内阅读</a><button data-source-import="${esc(d.id)}">导入原文</button>${d.url?`<a href="${esc(safeUrl(d.url))}" target="_blank" rel="noopener noreferrer">在线来源 ↗</a>`:''}</div></article>`).join('')}</div>`;
}
function annotationsShell(anchor){
  return head('划线与便签','长按/拖选原文后可高亮、划重点、下划线或留便签。这里集中管理全部批注，并可建立双向关联。')+`<div class="actions"><a class="btn" href="#/sources">回到原文书库</a></div><div id="annotation-list" data-anchor="${esc(anchor||'')}"><div class="empty">正在读取本机批注…</div></div>`;
}
async function hydrateSources(){
  const api=SR();if(!api)return;let list=[];try{list=await api.listSources();}catch(e){toast(e.message);}
  const map=new Map(list.map(x=>[x.paperId,x]));
  $('[data-source-card]').forEach(card=>{const src=map.get(card.dataset.sourceCard),st=card.querySelector('[data-source-status]');if(st)st.textContent=src?`已存本机：${src.name} · ${src.pages.length}段/页 · ${(src.size/1048576).toFixed(1)}MB · ${src.format.toUpperCase()}`:'尚未导入完整原文；带读和书目信息仍可离线。';});
}
async function hydrateAnnotations(anchor){
  const api=SR(),host=$('#annotation-list');if(!api||!host)return;
  let anns=[];try{anns=(await api.listAnnotations()).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));}catch(e){host.innerHTML='<div class="empty">'+esc(e.message)+'</div>';return;}
  if(!anns.length){host.innerHTML='<div class="empty">还没有划线或便签。进入任一“站内原文”，长按选择文字即可开始。</div>';return;}
  host.innerHTML=anns.map(a=>{const d=byId.get(a.paperId),linked=(a.links||[]).map(id=>anns.find(x=>x.id===id)).filter(Boolean);return `<article class="annotation-card" id="ann-${esc(a.id)}"><div class="annotation-meta">${esc(d?.title||a.paperId)} · 第${a.page}页/段 · ${esc(a.kind)}</div><blockquote>${esc(a.quote)}</blockquote>${a.note?`<p class="annotation-note">${esc(a.note)}</p>`:''}<div class="annotation-links">${linked.map(x=>`<a href="#/annotations/${esc(x.id)}">↔ ${esc((x.note||x.quote).slice(0,40))}</a>`).join('')}</div><div class="actions"><a class="btn" href="#/source/${esc(a.paperId)}/${esc(a.id)}">回到原文位置</a><select data-link-from="${esc(a.id)}"><option value="">选择要双向关联的便签</option>${anns.filter(x=>x.id!==a.id).map(x=>`<option value="${esc(x.id)}">${esc((x.note||x.quote).slice(0,55))}</option>`).join('')}</select><button data-link-ann="${esc(a.id)}">双向关联</button><button data-delete-ann="${esc(a.id)}">删除</button></div></article>`;}).join('');
  $('[data-delete-ann]').forEach(b=>b.onclick=async()=>{if(confirm('删除这条划线/便签？')){await api.deleteAnnotation(b.dataset.deleteAnn);hydrateAnnotations();}});
  $('[data-link-ann]').forEach(b=>b.onclick=async()=>{const sel=document.querySelector(`[data-link-from="${CSS.escape(b.dataset.linkAnn)}"]`);if(!sel?.value)return;await api.linkAnnotations(b.dataset.linkAnn,sel.value);hydrateAnnotations(b.dataset.linkAnn);toast('已建立双向关联。');});
  if(anchor){requestAnimationFrame(()=>document.getElementById('ann-'+anchor)?.scrollIntoView({block:'center'}));}
}
async function hydrateSource(paperId,anchor){
  const api=SR(),d=byId.get(paperId),host=$('#source-reader-body'),status=$('#source-local-status'),controls=$('#source-controls');if(!api||!d||!host)return;
  let src;try{src=await api.getSource(paperId);}catch(e){host.innerHTML='<div class="empty">'+esc(e.message)+'</div>';return;}
  if(!src){status.textContent='尚未导入完整原文。点击“导入/替换原文”选择PDF、HTML、TXT或Markdown；导入后文件只保存在本设备。';host.innerHTML=`<div class="empty"><p>带读页面仍然完整可用，但站内“原文”不会从第三方网站偷偷复制全文。</p><p>若你已有论文PDF：导入后会在本机提取文字，连续阅读、翻页、划线和便签均可离线使用；原PDF仍保留，可通过分享菜单交给WPS等外部阅读器。</p></div>`;return;}
  status.textContent=`本机原文：${src.name} · ${src.pages.length}页/段 · ${(src.size/1048576).toFixed(1)}MB · 导入于 ${new Date(src.importedAt).toLocaleString()}`;
  controls.classList.remove('hidden');
  const anns=await api.listAnnotations(paperId),byPage=new Map();for(const a of anns){if(!byPage.has(a.page))byPage.set(a.page,[]);byPage.get(a.page).push(a);}
  host.innerHTML=`<div class="source-pages ${store.sourceMode==='paged'?'paged':'scroll'}">${src.pages.map(p=>`<section class="source-text-page" data-source-page="${p.n}"><div class="source-page-label">原文件第 ${p.n} 页/段</div><div class="source-page-body" data-page="${p.n}">${api.renderAnnotatedText(p.text,byPage.get(p.n)||[])}</div></section>`).join('')}</div>`;
  const flow=host.querySelector('.source-pages');
  if(store.sourceMode==='paged'&&Number.isFinite(store.sourcePageX[paperId]))flow.scrollLeft=store.sourcePageX[paperId];
  flow.addEventListener('scroll',()=>{if(store.sourceMode==='paged'){store.sourcePageX[paperId]=flow.scrollLeft;persist();}},{passive:true});
  const setMode=m=>{store.sourceMode=m;persist();hydrateSource(paperId,anchor);};
  $('#source-mode-scroll').onclick=()=>setMode('scroll');$('#source-mode-page').onclick=()=>setMode('paged');
  $('#source-prev').onclick=()=>flow.scrollBy({left:-Math.max(300,flow.clientWidth*.92),behavior:'smooth'});
  $('#source-next').onclick=()=>flow.scrollBy({left:Math.max(300,flow.clientWidth*.92),behavior:'smooth'});
  $('#source-share').onclick=async()=>{try{const x=await api.shareSource(paperId);toast(x==='shared'?'已打开系统分享菜单，可选择WPS等阅读器。':'当前浏览器不支持文件分享，已改为下载原文件。');}catch(e){toast(e.message);}};
  $('#source-download').onclick=async()=>{try{await api.exportSource(paperId);}catch(e){toast(e.message);}};
  installSourceSelection(paperId);
  if(anchor){const a=await api.getAnnotation(anchor);if(a){requestAnimationFrame(()=>{const el=host.querySelector(`[data-ann-ids*="${CSS.escape(anchor)}"]`);el?.scrollIntoView({block:'center',inline:'center'});el?.classList.add('annotation-target');});}}
}
function installSourceSelection(paperId){
  const api=SR(),toolbar=$('#selection-tools');if(!api||!toolbar)return;
  const update=()=>{const sel=window.getSelection();if(!sel||sel.isCollapsed){toolbar.hidden=true;sourceSelection=null;return;}const node=sel.anchorNode?.nodeType===1?sel.anchorNode:sel.anchorNode?.parentElement,body=node?.closest?.('.source-page-body');if(!body||!body.contains(sel.focusNode)){toolbar.hidden=true;sourceSelection=null;return;}const off=api.selectionOffsets(body,sel);if(!off){toolbar.hidden=true;return;}sourceSelection={paperId,page:Number(body.dataset.page),...off};toolbar.hidden=false;};
  document.onselectionchange=()=>setTimeout(update,0);update();
  $('[data-ann-kind]').forEach(b=>b.onclick=async()=>{if(!sourceSelection)return;let note='';if(b.dataset.annKind==='note'){note=prompt('写下这条便签（只保存在本设备）','')||'';if(!note.trim())return;}try{const a=await api.saveAnnotation({...sourceSelection,kind:b.dataset.annKind,note});window.getSelection()?.removeAllRanges();sourceSelection=null;toolbar.hidden=true;await hydrateSource(paperId,a.id);toast('已保存批注。');}catch(e){toast(e.message);}});
  $('[data-ann-cancel]').onclick=()=>{window.getSelection()?.removeAllRanges();sourceSelection=null;toolbar.hidden=true;};
}
function bindSourceControls(){
  $('[data-source-import]').forEach(b=>b.onclick=()=>{pendingSourcePaper=b.dataset.sourceImport;$('#source-file').click();});
}

function render(restore=false){route=decodeURIComponent(location.hash.replace(/^#\/?/,''))||'home';const [id,section,extra]=route.split('/');document.title=(id==='source'?(byId.get(section)?.title||'原文阅读'):id==='sources'?'原文书库':id==='annotations'?'划线与便签':(byId.get(id)?.title||'农业系统论文带读'))+' · Paper Lab';document.onselectionchange=null;$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');$$('.sidebar a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#/'+id));$('#breadcrumb').textContent=byId.get(id)?.stage||'学习工作台';let out;if(id==='home')out=home();else if(['library','methods'].includes(id))out=library(id);else if(id==='notes')out=notes();else if(id==='sources')out=sourcesShell();else if(id==='annotations')out=annotationsShell(section);else if(id==='source')out=sourceShell(section,extra);else if(id==='offline')out=offline();else if(id==='lab')out=lab();else if(id==='search')out=searchPage(section||'');else if(byId.has(id))out=article(byId.get(id));else out=head('没有找到这篇内容','链接可能来自另一版本。')+link('home','返回学习总览');const y=restore?(history.state?.y||0):0;restoreLock=true;$('#view').innerHTML=out;bind();bindSourceControls();if(id==='sources')hydrateSources();if(id==='annotations')hydrateAnnotations(section);if(id==='source')hydrateSource(section,extra);requestAnimationFrame(()=>{if(restore)scrollTo(0,y);else if(section&&document.getElementById(section))document.getElementById(section).scrollIntoView();else scrollTo(0,0);requestAnimationFrame(()=>{restoreLock=false;savePosition();});});}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||e.defaultPrevented||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||e.button!==0)return;const href=a.getAttribute('href');if(href?.startsWith('#/')){e.preventDefault();go(href);}});
$('#search-form').onsubmit=e=>{e.preventDefault();go('#/search/'+encodeURIComponent($('#search').value));};
$('#menu').onclick=()=>{const on=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(on));};
$('#theme').onclick=()=>{store.dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',store.dark);persist();};
$('#back').onclick=()=>{savePosition();if(history.length>1)history.back();else go('#/home');};
$('#resume').onclick=()=>{if(store.last&&byId.has(store.last))go('#/'+store.last,{restore:true});else go('#/liang-2022');};
$('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>4e6)throw Error('备份超过4MB');const obj=JSON.parse(await f.text());if(obj.schema!==KEY||!obj.data||typeof obj.data!=='object')throw Error('不是本站学习备份');for(const k of ['notes','done','positions'])for(const [id,v] of Object.entries(obj.data[k]||{})){if(!byId.has(id))continue;if(k==='notes'&&typeof v==='string'){if(store.notes[id]&&store.notes[id]!==v)store.notes[id]+='\n\n--- 导入的笔记 ---\n'+v;else store.notes[id]=v;}if(k==='done'&&typeof v==='boolean')store.done[id]=!!store.done[id]||v;if(k==='positions'&&v&&typeof v.route==='string'&&v.route.startsWith('#/'+id)&&Number.isFinite(v.y))store.positions[id]={route:v.route,y:Math.max(0,v.y),at:v.at||0};}persist();render(true);toast('已合并；现有笔记不会被静默覆盖。');}catch(err){toast('导入失败：'+err.message);}e.target.value='';};

$('#source-file').onchange=async e=>{const f=e.target.files[0],paperId=pendingSourcePaper;e.target.value='';pendingSourcePaper=null;if(!f||!paperId)return;const d=byId.get(paperId);try{toast('正在把原文保存在本机并提取阅读文字…');await SR().importFile(paperId,f,{title:d?.en||d?.title||paperId},(i,n)=>{const st=$('#source-local-status');if(st)st.textContent=`正在解析PDF：${i}/${n}页…`;});toast('原文已保存到本设备，可断网阅读。');if(route.startsWith('source/'+paperId))await hydrateSource(paperId);else if(route==='sources')await hydrateSources();}catch(err){toast('原文导入失败：'+err.message);}};
window.addEventListener('popstate',()=>render(true));window.addEventListener('hashchange',()=>{if(decodeURIComponent(location.hash.replace(/^#\/?/,''))!==route)render(false);});
let scrollTimer;window.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(savePosition,130);},{passive:true});window.addEventListener('pagehide',savePosition);
const net=()=>{const n=$('#network');n.textContent=navigator.onLine?'在线 / 可缓存':'离线阅读';n.classList.toggle('off',!navigator.onLine);};window.addEventListener('online',net);window.addEventListener('offline',net);net();
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});
$('#priority').innerHTML=['liang-2022','liang-2023','farmsteps-2026','cheng-2023','cheng-2025','xu-2024'].map(id=>link(id,byId.get(id)?.title)).join('');$('#version').textContent='内容版本 '+D.version+' · '+D.updated;
document.body.classList.toggle('dark',store.dark??matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.style.setProperty('--body-size',(store.font||17)+'px');if(!history.state?.pl)history.replaceState({pl:true,y:0},'',location.href);render(true);
if('serviceWorker' in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).then(r=>{registration=r;const notify=()=>{$('#update-banner').hidden=false;};if(r.waiting)notify();r.addEventListener('updatefound',()=>{const w=r.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)notify();});});}).catch(()=>{if($('#cache-status'))$('#cache-status').textContent='服务工作线程注册失败；可下载单文件离线版。';});let updating=false;$('#apply-update').onclick=()=>{savePosition();updating=true;registration?.waiting?.postMessage({type:'SKIP_WAITING'});};navigator.serviceWorker.addEventListener('controllerchange',()=>{if(updating)location.reload();});}
})();
