/* Source-scoped inline explanations. No private data, source-text edits or network calls. */
(()=>{'use strict';
const D=window.PAPER_CONTEXT||{entries:[]},rows=new Map((D.entries||[]).map(x=>[x.id,x]));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let active=null,origin=null;
function safeLink(s){if(typeof s!=='string')return '';if(/^#\/[a-z0-9-]+(?:\/[a-zA-Z0-9_-]+){0,2}$/.test(s))return s;try{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
function link(r){const href=safeLink(r.href);return href?`<a href="${E(href)}"${href.startsWith('https:')?' target="_blank" rel="noopener noreferrer"':''}>${E(r.label)}</a>`:`<span>${E(r.label)}</span>`;}
function close(restore=true){if(!active)return;const old=origin;origin=null;const d=active;active=null;d.close();d.remove();if(old?.isConnected){old.setAttribute('aria-expanded','false');if(restore)old.focus({preventScroll:true});}}
function open(button){const r=rows.get(button.dataset.contextNote);if(!r)return;if(origin===button){close();return;}close(false);origin=button;button.setAttribute('aria-expanded','true');
 const d=document.createElement('dialog');d.id='paper-context-note';d.className='context-note-dialog';d.setAttribute('aria-labelledby','context-note-title');d.setAttribute('aria-modal','true');d.innerHTML=`<header class="context-note-header"><div><small>${E(r.evidenceLabel||'本文上下文 · 来源可定位')}</small><h2 id="context-note-title">${E(r.title)}</h2></div><button type="button" class="context-note-close" aria-label="关闭本文解释">×</button></header><div class="context-note-body"><p class="context-note-lead">${E(r.summary)}</p>${(r.sections||[]).map(s=>`<section><h3>${E(s.title)}</h3>${(s.paragraphs||[]).map(p=>`<p>${E(p).replace(/\n/g,'<br>')}</p>`).join('')}${s.items?`<ul>${s.items.map(v=>`<li>${E(v)}</li>`).join('')}</ul>`:''}</section>`).join('')}${r.details?.length?`<div class="context-note-details">${r.details.map(v=>`<details><summary>${E(v.title)}</summary>${(v.paragraphs||[]).map(p=>`<p>${E(p).replace(/\n/g,'<br>')}</p>`).join('')}</details>`).join('')}</div>`:''}<section class="context-note-sources"><h3>原文与完整讲解</h3><p>${E(r.sourceLocation||'')}</p><div>${(r.links||[]).map(link).join('')}</div></section>${r.boundary?`<p class="context-note-boundary">${E(r.boundary)}</p>`:''}</div>`;
 document.body.append(d);active=d;d.querySelector('.context-note-close').onclick=()=>close();d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('keydown',e=>{if(e.key!=='Tab'||e.altKey||e.ctrlKey||e.metaKey)return;const focusable=[...d.querySelectorAll('button,a[href],input,select,textarea,summary,[tabindex]:not([tabindex="-1"])')].filter(x=>!x.disabled&&x.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(!first)return;const here=document.activeElement;if(e.shiftKey&&(here===first||!d.contains(here))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(here===last||!d.contains(here))){e.preventDefault();first.focus();}});d.addEventListener('click',e=>{if(e.target===d){const box=d.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)close();}});d.addEventListener('click',e=>{if(e.target.closest('a[href^="#/"]'))close(false);});d.showModal();d.querySelector('.context-note-close').focus({preventScroll:true});
}
function decorate(target,r){
 const needles=[...new Set(r.phrases||[])].filter(x=>typeof x==='string'&&x.length>0).sort((a,b)=>b.length-a.length);if(!needles.length)return;
 const walker=document.createTreeWalker(target,NodeFilter.SHOW_TEXT,{acceptNode:n=>{const p=n.parentElement;return !p||!n.textContent.trim()||p.closest('button,a,input,textarea,select,pre,code,math,mark,.source-note,.research-section-tools,.method-contract,.term-word,[data-no-terms]')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT;}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 for(const node of nodes){let text=node.textContent,at=0,found=false;const frag=document.createDocumentFragment();while(at<text.length){let next=-1,phrase='';for(const n of needles){const i=text.indexOf(n,at);if(i!==-1&&(next===-1||i<next||(i===next&&n.length>phrase.length))){next=i;phrase=n;}}if(next===-1)break;frag.append(document.createTextNode(text.slice(at,next)));const b=document.createElement('button');b.type='button';b.className='context-note-trigger';b.dataset.contextNote=r.id;b.setAttribute('aria-haspopup','dialog');b.setAttribute('aria-expanded','false');b.setAttribute('aria-controls','paper-context-note');b.setAttribute('aria-label',phrase+'：查看本文具体解释');b.textContent=phrase;frag.append(b);at=next+phrase.length;found=true;}if(found){frag.append(document.createTextNode(text.slice(at)));node.replaceWith(frag);}}
}
function mountLesson(id,root){if(!root||!/^[-a-z0-9]+$/.test(id))return;close(false);for(const r of D.entries||[]){if(r.pageId!==id||!/^s\d+$/.test(r.sectionId))continue;const section=root.querySelector('#'+r.sectionId);if(!section)continue;for(const t of section.querySelectorAll(':scope > h2,:scope > h3,:scope > .prose'))decorate(t,r);}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-context-note]');if(!b)return;if(getSelection()?.toString().trim())return;e.preventDefault();e.stopPropagation();open(b);});
addEventListener('hashchange',()=>close(false));addEventListener('pagehide',()=>close(false));
window.PaperContext={mountLesson,close,isOpen:()=>!!active,version:D.version||'5.5.4'};
})();
