/* Evidence and practice are separate from reading progress. No automatic mastery score. */
(()=>{'use strict';const C=window.PAPER_CONTRACTS?.contracts||{},D=new Map((window.PAPER_DATA?.documents||[]).map(d=>[d.id,d]));const cache=new Map();
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function link(id,label){const a=el('a',label||D.get(id)?.title||id);a.href='#/'+id;return a;}
function prose(text){const p=el('p',text,'prose');return p;}
function detail(title,body,open=false){const d=el('details',undefined,'method-contract-part');d.open=open;d.append(el('summary',title));for(const node of body)d.append(node);return d;}
function note(parent,id,kind,label){if(typeof window.PaperResearch?.noteBox!=='function')throw Error('Research note storage is not ready');const box=PaperResearch.noteBox(id,'method-contract-'+kind,label,true);const input=box.querySelector('textarea');if(input)input.placeholder='记录你自己的推导、证据或疑问；所有记录自愿填写，不影响阅读。';parent.append(box);}
function make(id,c){const root=el('section',undefined,'method-contract');root.id='method-contract';root.dataset.contract=id;root.append(el('span','METHOD LEDGER · 从原始资料到可检验理解','eyebrow'),el('h2','先把这篇研究完整接通'),prose(c.question));
 const flow=el('div',undefined,'contract-flow');for(const [k,t] of [['研究对象',c.object],['中间过程',c.process.map((s,i)=>(i+1)+'. '+s).join('\n')],['最终输出',c.outputs]]){const p=el('div');p.append(el('h3',k),prose(t));flow.append(p);}root.append(flow);
 const ev=detail('1．原文依据与目前证据范围',[prose(c.evidence)]);const b=el('button','就地展开本页原文段落与图');b.type='button';b.onclick=()=>{const target=document.querySelector('.research-bridge .research-evidence');if(target){target.open=true;target.scrollIntoView({block:'start'});}else{const a=link('original/'+id,'进入站内原文并核对获取状态');ev.append(a);b.disabled=true;}};ev.append(b);ev.append(link('original/'+id,'进入站内完整原文 →'));for(const r of c.authorResources||[]){const u=new URL(r.url);if(u.protocol!=='https:')continue;const a=el('a',r.label);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';const row=el('p');row.append(a,el('small',' '+r.status));ev.append(row);}note(ev,id,'evidence','原文的哪一处还需要补查？');root.append(ev);
 const wrap=el('div',undefined,'tablewrap');const table=el('table');const head=el('thead');const tr=el('tr');for(const h of ['字段或数据组','一行代表什么','形式／单位','为什么必需'])tr.append(el('th',h));head.append(tr);const body=el('tbody');for(const row of c.inputs){const r=el('tr');for(const x of row)r.append(el('td',x));body.append(r);}table.append(head,body);wrap.append(table);const inp=detail('2．输入数据结构：哪些表、哪些单位、怎样对应',[wrap,prose('这是按论文方法整理的数据结构说明，不是作者原始CSV文件名。未拿到作者数据时，不将这里的字段组织冒充已获取的原始数据字典。')]);note(inp,id,'inputs','输入表、单位与连接关系的备忘');root.append(inp);
 const method=detail('3．怎样计算或生成方案：逐步说明每个转换',[...c.process.map((s,i)=>{const p=el('div',undefined,'contract-step');p.append(el('h3','步骤 '+(i+1)),prose(s));return p;}),el('h3','得到什么'),prose(c.outputs)]);note(method,id,'process','我的手算、流程重建与卡住的位置');root.append(method);
 const prac=detail('4．带解说的复现示例：输入、输出与范围',[el('span',(window.PaperLibrary?.explain(c.practice.kind)||c.practice.kind),'pill'),prose(window.PaperLibrary?.explain(c.practice.do)||c.practice.do)]);prac.append(el('pre','python paper_minilab.py --case '+c.practice.case+'\npython paper_minilab.py --test'));const a=el('a','下载可运行的标准库教学脚本');const exercise=window.PAPER_DATA?.files?.['paper_minilab.py'];if(document.body.classList.contains('single')){if(typeof exercise==='string')a.href = 'data:text/x-python;charset=utf-8,'+encodeURIComponent(exercise);else a.remove();}else a.href = new URL('examples/paper_minilab.py',document.baseURI).href;a.download='paper_minilab.py';prac.append(a,el('h3','结果怎样解释'),prose(c.practice.expect),el('h3','该示例尚未复现什么'),prose(c.practice.notReproduced));note(prac,id,'reproduction','保存我的运行结果、差异、修改和解释');root.append(prac);
 const gaps=detail('5．最重要的限制、未解决问题及海南迁移',[el('h3','不能越过的结论边界'),prose(c.limits),...c.gaps.map((g,i)=>prose('待核 '+(i+1)+'：'+g)),el('h3','我能借鉴哪一步'),prose(c.transfer)]);const links=el('div',undefined,'tags');for(const target of c.links)links.append(link(target));gaps.append(links);note(gaps,id,'research','对我的研究候选、变量与海南调研意味着什么？');root.append(gaps);
 const mastery=detail('6．研究备忘：解释、适用边界与下一步',[prose('可按研究需要记录解释、适用边界、运行差异和待查证据，所有小框均为可选。旧记录继续保留；材料或复现未齐时明确标记缺口。')]);note(mastery,id,'explain','对象、输入、过程与输出的研究备忘');note(mastery,id,'counterexample','适用边界、反例与不满足的约束');note(mastery,id,'next-action','下一步待补材料与验证安排');root.append(mastery);return root;}
function mount(){let route;try{route=decodeURIComponent(location.hash.split('/')[1]||'');}catch{return;}const root=document.querySelector('#view .reader');if(!root||!C[route]||root.querySelector('.method-contract')||typeof window.PaperResearch?.noteBox!=='function')return;const block=cache.get(route)||make(route,C[route]);for(const box of block.querySelectorAll('.research-note-box')){const f=box.querySelector('textarea');if(f&&document.activeElement!==f){try{const value=JSON.parse(localStorage.getItem('paper-lab-learning-v1')||'{}').notes?.[box.dataset.noteKey]||'';f.value=value;f._researchBase=value;}catch{}}}cache.set(route,block);if(cache.size>12)cache.delete(cache.keys().next().value);const head=root.querySelector('.articlehead');if(head)head.after(block);}
window.PaperContracts={mount,ids:()=>Object.keys(C),version:'1.0'};
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;mount();});}).observe(document.querySelector('#view')||document.body,{childList:true,subtree:true});addEventListener('hashchange',mount);mount();
})();
