/* Source-anchored guided reading. Archive text/IDs/hashes never rewritten.
   Exact source is rendered from licensed/local books, not reconstructed prose. */
(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cfg=window.PAPER_EVIDENCE||{documents:{}},norm=t=>String(t||'').replace(/\s+/g,' ').trim();let generation=0,urls=[];
const safe=p=>typeof p==='string'&&p.startsWith('library/')&&!p.split('/').includes('..')?p:'';
function text(content,id,cls='evidence-explanation'){return '<p class="'+cls+'" id="'+E(id)+'" data-block="'+E(id)+'">'+E(content).replace(/\n/g,'<br>')+'</p>';}
function zoom(src,label){const d=document.createElement('dialog');d.className='evidence-zoom';d.innerHTML='<header><strong></strong><button class="zoom-size">放大 / 适应宽度</button><button class="zoom-close">关闭</button></header><div class="evidence-image-scroll"><img alt="原文证据图"></div>';d.querySelector('strong').textContent=label;const img=d.querySelector('img');img.src=src;$('.zoom-size',d).onclick=()=>img.classList.toggle('wide');$('.zoom-close',d).onclick=()=>d.close();d.onclose=()=>d.remove();document.body.append(d);d.showModal();}
async function imageURL(book,value){if(!book.local)return safe(value);const row=await window.PaperReader.all('files');const blob=row.find(x=>x.id===value)?.blob;if(!blob)return '';const u=URL.createObjectURL(blob);urls.push(u);return u;}
function tableMarkup(t,prefix){return '<div class="tablewrap evidence-table"><table><caption>'+E(t.title||'指标总表')+'</caption><thead><tr>'+t.columns.map(v=>'<th scope="col">'+E(v)+'</th>').join('')+'</tr></thead><tbody>'+t.rows.map((r,i)=>'<tr>'+r.map((v,j)=>'<'+(j===0?'th scope="row"':'td')+'>'+E(v)+'</'+(j===0?'th':'td')+'>').join('')+'</tr>').join('')+'</tbody></table></div>';}
async function source(card,spec,book,token){const slot=document.createElement('aside');slot.className='evidence-source';slot.dataset.sourceDoc=book.id;slot.dataset.sourceHash=book.sourceHash;slot.dataset.sourceTitle=book.title;slot.dataset.evidenceCard=card.id;slot.innerHTML='<div class="evidence-source-header"><strong>原文证据 · '+E(spec.locator||'指定段落')+'</strong><small>以下来自原件；解释和自编示例在此框之外。</small></div>';
 const blocks=new Map(book.pages.flatMap(p=>p.blocks).map(b=>[b.id,b]));let first=null;
 for(const id of spec.blocks||[]){const b=blocks.get(id);if(!b||!b.text)throw Error('指定原文段落不存在：'+id);const p=document.createElement('p');p.lang='en';p.className='evidence-original-text';p.id='ev-'+card.id+'-'+id;p.dataset.originalBlock=id;p.textContent=norm(b.text);slot.append(p);first||=id;}
 const groups=window.PAPER_LAYOUTS?.[book.id]?.sourceHash===book.sourceHash?window.PAPER_LAYOUTS[book.id].groups:[];
 for(const number of spec.equations||[]){const g=groups.find(x=>(x.numbers||[x.number]).includes(String(number)));if(!g)throw Error('原式尚无可靠定位：'+number);if(slot.querySelector('[data-equation-group="'+g.id+'"]'))continue;const figure=document.createElement('figure');figure.className='evidence-equation';figure.dataset.equationGroup=g.id;const img=document.createElement('img');img.src=safe(g.path);img.alt='原文公式 '+(g.numbers||[g.number]).join('、')+' 保真裁图';figure.append(img);const cap=document.createElement('figcaption');cap.textContent=img.alt+'（点击放大）';figure.append(cap);img.onclick=()=>zoom(img.src,cap.textContent);slot.append(figure);first||=g.blocks?.[0];}
 for(const item of spec.figures||[]){const b=blocks.get(item.block);const page=book.pages.find(p=>p.number===item.page);const target=b?.path||page?.snapshot;if(!target)throw Error('原图不存在');const path=await imageURL(book,target);if(token!==generation)return null;const figure=document.createElement('figure');figure.className='evidence-figure';figure.id='ev-'+card.id+'-fig-'+(item.block||item.page);const img=document.createElement('img');img.src=path;img.alt=item.title;img.loading='lazy';figure.append(img);const cap=document.createElement('figcaption');cap.textContent=item.title+' · '+(item.locator||spec.locator||'')+'（点击查看完整大图）';figure.append(cap);img.onclick=()=>zoom(path,item.title);
  if(item.reading)figure.insertAdjacentHTML('beforeend',text(item.reading,'guide-'+card.id+'-'+(item.block||item.page),'evidence-figure-reading'));
  const note=document.createElement('button');note.textContent='给这张原图留便签';note.onclick=()=>window.PaperReader.editNote(null,{docId:book.id,docTitle:book.title,sourceHash:book.sourceHash,block:item.block||'page-'+item.page,type:'note',segments:[],title:item.title});figure.append(note);
  const tag=document.createElement('div');tag.className='tags';tag.dataset.tagOwner='figure:'+book.id+':'+(item.block||'page-'+item.page);tag.dataset.defaultTags='[]';tag.dataset.noTerms='true';figure.append(tag);slot.append(figure);first||=item.block||'page-'+item.page;
 }
 if(first){const a=document.createElement('a');a.href='#/original/'+book.id+'/'+first;a.className='evidence-return';a.textContent='进入原文准确位置 ↗（浏览器后退可回到本段）';slot.append(a);}
 if(book.license?.name){const footer=document.createElement('small');footer.className='evidence-license';footer.textContent=book.citation+' · '+book.license.name+' · 原件校验 '+book.sourceHash.slice(0,12);slot.append(footer);}
 return slot;
}
async function mount(id){const token=++generation;urls.forEach(URL.revokeObjectURL);urls=[];const set=cfg.documents[id],root=$('#view .reader');if(!set||!root||root.dataset.evidenceMounted)return;root.dataset.evidenceMounted='v52';
 let book;try{book=await window.PaperReader.loadBook(set.source||id);}catch{}if(token!==generation||!root.isConnected)return;
 for(const panel of set.panels){const target=$('#'+panel.section,root);if(!target)continue;const wrap=document.createElement('div');wrap.className='evidence-panel';wrap.id='evidence-'+panel.id;wrap.innerHTML='<span class="eyebrow">DETAILS & SOURCE EVIDENCE</span><h3>'+E(panel.title)+'</h3>'+text(panel.overview,'detail-'+panel.id+'-overview')+(panel.table?tableMarkup(panel.table,panel.id):'');target.append(wrap);
  if(!book||book.sourceHash!==set.sourceHash){wrap.insertAdjacentHTML('beforeend','<p class="notice warn">未找到与本带读匹配的原件版本，或尚未缓存。不会用摘要代替这些原文证据；请从原文书架恢复对应版本。</p>');continue;}
  for(const [index,card]of panel.cards.entries()){card.id=panel.id+'-'+index;const detail=document.createElement(card.collapsed?'details':'div');detail.className='evidence-card';detail.id='detail-'+card.id;detail.innerHTML=(card.collapsed?'<summary>':'<h4>')+E(card.title)+(card.collapsed?'</summary>':'</h4>');
   for(const [j,part]of (card.parts||[]).entries())detail.insertAdjacentHTML('beforeend','<h5>'+E(part.label)+'</h5>'+text(part.text,'detail-'+card.id+'-'+j));
   if(card.source)try{const node=await source(card,card.source,book,token);if(node)detail.append(node);}catch(e){detail.insertAdjacentHTML('beforeend','<p class="notice warn">证据暂不可用：'+E(e.message)+'。请从原文入口核对，未自动换用其他段落。</p>');}
   if(token!==generation||!root.isConnected)return;wrap.append(detail);
  }
 }
 window.PaperStudy?.terms(root);await paint();window.PaperComfort?.enhanceLesson();
 document.dispatchEvent(new CustomEvent('paper-evidence-ready',{detail:{id}}));
}
function captureSelection(range){const roots=$$('.evidence-source').filter(r=>range.intersectsNode(r));if(!roots.length)return undefined;const common=range.commonAncestorContainer.nodeType===1?range.commonAncestorContainer:range.commonAncestorContainer.parentElement;const host=common.closest('.evidence-source');if(!host||roots.length!==1)return null;
 const segments=[];for(const p of $$('[data-original-block]',host)){if(!range.intersectsNode(p))continue;const offset=(node,n)=>{const r=document.createRange();r.selectNodeContents(p);r.setEnd(node,n);return r.toString().length;};const start=p.contains(range.startContainer)?offset(range.startContainer,range.startOffset):0,end=p.contains(range.endContainer)?offset(range.endContainer,range.endOffset):p.textContent.length;if(end>start)segments.push({block:p.dataset.originalBlock,start,end,quote:p.textContent.slice(start,end),prefix:p.textContent.slice(Math.max(0,start-40),start),suffix:p.textContent.slice(end,end+40)});}
 return segments.length?{docId:host.dataset.sourceDoc,sourceHash:host.dataset.sourceHash,docTitle:host.dataset.sourceTitle,segments,quote:segments.map(s=>s.quote).join('\n')}:null;
}
async function paint(){const roots=$$('.evidence-source');if(!roots.length)return;const notes=await window.PaperReader.all('annotations');for(const host of roots){for(const old of $$('mark[data-annotation]',host))old.replaceWith(...old.childNodes);host.normalize();for(const n of notes.filter(x=>x.docId===host.dataset.sourceDoc&&(!x.sourceHash||x.sourceHash===host.dataset.sourceHash))){for(const s of n.segments||[]){const targets=$$('[data-original-block]',host).filter(p=>p.dataset.originalBlock===s.block);for(const p of targets){if(p.textContent.slice(s.start,s.end)!==s.quote)continue;const w=document.createTreeWalker(p,NodeFilter.SHOW_TEXT);let at=0,nodes=[];while(w.nextNode()){const node=w.currentNode;nodes.push([node,at,at+node.length]);at+=node.length;}for(const [node,a,z]of nodes.reverse()){const lo=Math.max(a,s.start)-a,hi=Math.min(z,s.end)-a;if(hi<=lo)continue;const r=document.createRange();r.setStart(node,lo);r.setEnd(node,hi);const mark=document.createElement('mark');mark.dataset.annotation=n.id;mark.className='annotation-mark color-'+(['yellow','green','pink','blue'].includes(n.color)?n.color:'yellow')+(n.type==='underline'?' underline':'');r.surroundContents(mark);mark.onclick=e=>{e.stopPropagation();window.PaperReader.editNote(n);};}}}}}
}
window.PaperEvidence={mount,paint,captureSelection,version:'5.2.0'};
})();
