/* Personal entry v1: a private user-held capability, never a public shared PAT.
   Authenticated ciphertext + non-extractable CryptoKey are isolated from all backups. */
(()=>{'use strict';
const DB='paper-personal-device-v1',STORE='entry',AAD=new TextEncoder().encode('PaperLab.personal-entry.v1');
const enc=new TextEncoder(),dec=new TextDecoder();let database,record=null,working=false,confirmed=false,paused=false,retry=null,delay=15000,booting=false;
let state={state:'unconfigured',message:'普通公开入口不含私人授权',candidate:null,verified:[],durable:false};
const $=s=>document.querySelector(s),b64=b=>{let s='';for(const x of new Uint8Array(b))s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');};
function un64(s,max=18000){if(typeof s!=='string'||s.length>max||! /^[A-Za-z0-9_-]+$/.test(s))throw Error('专属入口格式无效');return Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));}
function emit(update){state={...state,...update};document.dispatchEvent(new CustomEvent('paper-personal-status',{detail:{...state}}));draw();}
async function db(){if(database)return database;database=await new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});return database;}
async function io(method,value){const d=await db();return new Promise((ok,no)=>{const t=d.transaction(STORE,method==='get'?'readonly':'readwrite'),r=t.objectStore(STORE)[method](value);let result;r.onsuccess=()=>result=r.result;t.oncomplete=()=>ok(result);t.onerror=t.onabort=()=>no(Error('本机无法保存专属入口；现有笔记未删除'));});}
function envelope(x){if(!x||x.schema!=='paper.personal.envelope.v1'||x.algorithm!=='AES-GCM-256'||un64(x.iv).length!==12||un64(x.ciphertext).length>14000)throw Error('专属入口版本或长度不受支持');return x;}
function payload(x){if(!x||x.schema!=='paper.personal.payload.v1'||x.repository!=='1337816143/My-Evolution'||! /^paper-user-data(?:-test-\d+)?$/.test(x.branch)||!Array.isArray(x.candidates)||x.candidates.length<1||x.candidates.length>2||x.candidates.some(t=>typeof t!=='string'||! /^(?:github_pat_|gh[opusr]_)[A-Za-z0-9_.-]{16,4096}$/.test(t)))throw Error('专属入口只允许指定的私有论文数据仓库');return x;}
async function decrypt(r){const e=envelope(r.envelope);try{return payload(JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(e.iv),additionalData:AAD,tagLength:128},r.key,un64(e.ciphertext)))));}catch{throw Error('专属入口无法解密或校验；没有读取或改写私人数据');}}
function takeFragment(){if(!location.hash.startsWith('#/personal/'))return null;const fragment=location.hash.slice(11);history.replaceState(null,'',location.pathname+location.search+'#/research-studio');return fragment;}
// Capture immediately, before app.js can store a URL or history entry containing it.
let initialFragment=takeFragment();
async function accept(fragment){const pieces=fragment.split('.');if(pieces.length!==2)throw Error('专属入口格式无效');const keyBytes=un64(pieces[1],100);if(keyBytes.length!==32)throw Error('专属入口密钥长度不正确');const e=envelope(JSON.parse(dec.decode(un64(pieces[0]))));const key=await crypto.subtle.importKey('raw',keyBytes,{name:'AES-GCM'},false,['decrypt']);keyBytes.fill(0);const candidate={id:'active',envelope:e,key,selected:null,paused:false,updatedAt:new Date().toISOString()};const checked=await decrypt(candidate);checked.candidates.fill('');if(working||window.PaperSync?.status().busy)throw Error('当前同步尚未结束，原有连接和笔记保留');await io('put',candidate);record=await io('get','active');if(record.key.extractable!==false)throw Error('不接受可导出的本机密钥');window.PaperSync?.disconnect();confirmed=false;paused=false;delay=15000;emit({state:'stored',durable:true,message:'专属入口已加密保存在本设备，正在自动连接'});return resume();}
async function resume(){if(working||paused||!record)return;if(!navigator.onLine){emit({state:'offline',message:'离线可继续记笔记，联网后自动恢复连接'});return;}if(!window.PaperSync){schedule();return;}if(PaperSync.status().connected){try{await PaperSync.sync();if(PaperSync.status().state==='synced')emit({state:'connected',message:'私有数据已核对；自动连接保持有效'});}catch(e){if(e.http===401){PaperSync.disconnect();schedule();}else emit({state:'pending',message:'本地数据保留，等待网络恢复或下一次自动同步'});}return;}
 working=true;emit({state:'connecting',message:'自动检查私有仓库及实际写入权限…'});
 try{const p=await decrypt(record);const indexes=[...(Number.isInteger(record.selected)?[record.selected]:[]),...p.candidates.map((_,i)=>i)].filter((n,i,a)=>a.indexOf(n)===i);let connected=false;
 for(const i of indexes){try{await PaperSync.connect({repository:p.repository,branch:p.branch},p.candidates[i]);record.selected=i;record.updatedAt=new Date().toISOString();await io('put',record);confirmed=true;connected=true;delay=15000;emit({state:'connected',candidate:i+1,verified:[...new Set([...state.verified,i+1])],durable:true,message:'已自动连接并完成私有数据核对；无需手填令牌'});break;}catch(e){emit({state:'checking',message:e.http?'授权候选验证未通过（HTTP '+e.http+'），不改动已有笔记':'本次连接未完成，本机笔记保留'});if(!navigator.onLine)break;}}
 p.candidates.fill('');if(!connected){emit({state:'pending',message:'尚未获得云端确认；会自动重试。同步详情保留具体网络或权限原因'});schedule();}
 }catch{emit({state:'error',message:'本机专属入口校验失败；原有笔记保留，请重新打开自己的入口文件'});}finally{working=false;draw();}}
function schedule(){clearTimeout(retry);if(!paused&&record){retry=setTimeout(()=>resume().catch(()=>{}),delay);delay=Math.min(delay*2,300000);}}
async function pause(){paused=true;clearTimeout(retry);window.PaperSync?.disconnect();if(record){record.paused=true;await io('put',record);}emit({state:'paused',message:'自动连接已暂停，本机和云端数据均保留'});}
async function activate(){paused=false;if(record){record.paused=false;await io('put',record);}return resume();}
async function forget(){if(!confirm('仅移除本设备的自动连接授权；论文、笔记和云端数据不会删除。继续？'))return;await pause();await io('delete','active');record=null;confirmed=false;emit({state:'unconfigured',durable:false,message:'本设备自动连接已移除，私人笔记仍保留'});}
async function recovery(){if(!record)throw Error('本机尚无专属入口');const p=await decrypt(record),raw=crypto.getRandomValues(new Uint8Array(32)),iv=crypto.getRandomValues(new Uint8Array(12));const k=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt']);const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:AAD,tagLength:128},k,enc.encode(JSON.stringify(p)));p.candidates.fill('');const e={schema:'paper.personal.envelope.v1',algorithm:'AES-GCM-256',iv:b64(iv),ciphertext:b64(cipher)};const suffix=b64(enc.encode(JSON.stringify(e)))+'.'+b64(raw);raw.fill(0);return 'https://1337816143.github.io/Paper/#/personal/'+suffix;}
function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>Promise.resolve(fn()).catch(()=>emit({message:'操作未完成；现有数据保留'}));return b;}
function draw(){const view=$('#view');if(!view)return;const form=$('#vault-connect');if(form)form.hidden=!!record;if(location.hash!=='#/sync')return;let box=$('#personal-status-panel');if(!box){box=document.createElement('section');box.id='personal-status-panel';box.className='card personal-status-panel';view.prepend(box);}box.replaceChildren();const h=document.createElement('h2');h.textContent=record?'专属入口 · 自动连接':'私人数据需要你的专属入口';const p=document.createElement('p');p.textContent=record?state.message:'此公共网站没有预置任何人的私有仓库密钥。请打开给你的专属入口文件；不需要填写或粘贴令牌。';box.append(h,p);
 if(record){const actions=document.createElement('div');actions.className='actions';actions.append(button(paused?'恢复自动连接':'立即核对',activate),button('暂停自动连接',pause),button('导出新设备入口',async()=>{if(!confirm('此入口能访问你的私有阅读库，请勿分享或上传。生成一个只供自己使用的入口？'))return;const url=await recovery(),html='<!doctype html><meta charset="utf-8"><meta name="referrer" content="no-referrer"><title>Paper 私人入口</title><p>正在打开私人论文阅读库，请勿分享此文件。</p><script>location.replace('+JSON.stringify(url).replace(/</g,'\\u003c')+');<\/script>';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));a.download='Paper-私人入口-勿分享.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);}),button('移除此设备授权',forget));box.append(actions);const tip=document.createElement('small');tip.textContent='自动保存不等于已上传：以“云端已确认”为准。另一设备打开同一专属入口后自动恢复；普通公开网址不能识别新设备是谁。专属入口本身是访问凭证。';box.append(tip);}}
async function boot(fragment=initialFragment){if(booting){if(fragment)setTimeout(()=>boot(fragment),80);return;}booting=true;initialFragment=null;try{if(fragment){await accept(fragment);fragment=null;}else{record=await io('get','active')||null;paused=!!record?.paused;if(record){const p=await decrypt(record);p.candidates.fill('');emit({state:paused?'paused':'stored',durable:true,message:paused?'自动连接已暂停':'正在恢复本设备自动连接'});if(!paused)await resume();}}}catch{emit({state:'error',message:'无法加载专属入口；英文原文与已有笔记仍可继续使用'});}finally{booting=false;draw();}}
window.PaperPersonal={version:'1.0',status:()=>({...state,busy:working,configured:!!record,paused}),safeToReload:()=>!!record&&!paused&&!working&&confirmed&&!window.PaperSync?.status().dirty,accept,resume:activate,pause,forget,recovery};
new MutationObserver(()=>{if(location.hash==='#/sync'&&!$('#personal-status-panel'))draw();}).observe(document.body,{childList:true,subtree:true});
addEventListener('online',()=>{if(record&&!paused)resume().catch(()=>{});});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&record&&!paused&&!window.PaperSync?.status().connected)resume().catch(()=>{});});document.addEventListener('paper-sync-status',()=>{if(record&&PaperSync.status().state==='synced'){confirmed=true;delay=15000;}draw();});
addEventListener('hashchange',event=>{const fragment=takeFragment();if(fragment){event.stopImmediatePropagation();queueMicrotask(()=>{dispatchEvent(new HashChangeEvent('hashchange'));boot(fragment);});}else draw();},true);
setTimeout(()=>boot(),0);
})();
