/* Pure two-response/two-predictor teaching model; no browser or private state. */
(function(global){'use strict';
const EPS=1e-12,COLUMNS=['crop_share_percent','distance_km','perception_a','perception_b'];
const sum=a=>a.reduce((s,v)=>s+v,0),mean=a=>sum(a)/a.length;
const transpose=a=>a[0].map((_,j)=>a.map(r=>r[j]));
const multiply=(a,b)=>{const t=transpose(b);return a.map(r=>t.map(c=>sum(r.map((v,i)=>v*c[i]))));};
function correlation(a,b){const am=mean(a),bm=mean(b),ac=a.map(v=>v-am),bc=b.map(v=>v-bm),den=Math.sqrt(sum(ac.map(v=>v*v))*sum(bc.map(v=>v*v)));return den>EPS?Math.max(-1,Math.min(1,sum(ac.map((v,i)=>v*bc[i]))/den)):null;}
function standardize(a){const cols=transpose(a),means=cols.map(mean),sds=cols.map((c,j)=>Math.sqrt(sum(c.map(v=>(v-means[j])**2))/(c.length-1)));if(Math.min(...sds)<=EPS)throw Error('常量列没有可用的标准差，不能标准化。');return {values:a.map(r=>r.map((v,j)=>(v-means[j])/sds[j])),means,sds};}
function eigen2(a){const x=a[0][0],y=a[0][1],z=a[1][1],delta=Math.hypot(x-z,2*y),values=[(x+z+delta)/2,(x+z-delta)/2];if(Math.min(...values)<-1e-10)throw Error('拟合协方差出现了不合法的负特征值。');for(let j=0;j<2;j++)values[j]=Math.max(0,values[j]);let v;if(Math.abs(y)<=EPS)v=x>=z?[1,0]:[0,1];else{const a=[y,values[0]-x],b=[values[0]-z,y];v=sum(a.map(v=>v*v))>=sum(b.map(v=>v*v))?a:b;const norm=Math.hypot(...v);v=v.map(x=>x/norm);}const vectors=[v,[-v[1],v[0]]].map(row=>{const k=Math.abs(row[0])>=Math.abs(row[1])?0:1;return row[k]<0?row.map(x=>-x):row;});return {values,vectors:transpose(vectors)};}
function number(value,key){if(value===null||value===undefined||typeof value==='boolean'||(typeof value==='string'&&!value.trim()))throw Error('缺少有效数值：'+key);const n=Number(value);if(!Number.isFinite(n))throw Error('需要有限数值：'+key);return n;}
function calculate(records,v4B){if(!Array.isArray(records)||records.length<4)throw Error('本讲解需要至少4行完整的合成村庄记录。');const ids=[],matrix=records.map(r=>{const id=String(r.village_id||'');if(!id||ids.includes(id))throw Error('村庄ID必须非空且唯一。');ids.push(id);return COLUMNS.map(k=>number(r[k],k));});if(v4B!==undefined){if(typeof v4B!=='number'||!Number.isFinite(v4B)||v4B<0||v4B>5)throw Error('V4的合成B得分需为0至5的有限数值。');const at=ids.indexOf('V4');if(at<0)throw Error('没有找到V4。');matrix[at][3]=v4B;}
const x=matrix.map(r=>r.slice(0,2)),y=matrix.map(r=>r.slice(2)),sx=standardize(x),sy=standardize(y),xs=sx.values,ys=sy.values,n=ids.length,xx=multiply(transpose(xs),xs),xy=multiply(transpose(xs),ys),[[a,b],[c,d]]=xx,det=a*d-b*c;
if(Math.abs(det)<EPS)throw Error('两个解释变量共线，XᵀX无法求逆；不要继续画出虚假的结果。');
const inverse=[[d/det,-b/det],[-c/det,a/det]],coef=multiply(inverse,xy),fit=multiply(xs,coef),residual=ys.map((r,i)=>r.map((v,j)=>v-fit[i][j])),fitRaw=fit.map(r=>r.map((v,j)=>v*sy.sds[j]+sy.means[j])),residualRaw=y.map((r,i)=>r.map((v,j)=>v-fitRaw[i][j]));
const inertia=m=>sum(m.flat().map(v=>v*v))/(n-1),total=inertia(ys),constrained=inertia(fit),unconstrained=inertia(residual),covariance=multiply(transpose(fit),fit).map(r=>r.map(v=>v/(n-1))),eigen=eigen2(covariance),axes=multiply(fit,eigen.vectors),observedAxes=multiply(ys,eigen.vectors),axisColumns=transpose(axes),xc=transpose(xs).map(col=>axisColumns.map(axis=>correlation(col,axis))),yc=transpose(ys).map(col=>axisColumns.map(axis=>correlation(col,axis)));
const cosine=(a,b)=>{if(a.includes(null)||b.includes(null))return null;const den=Math.sqrt(sum(a.map(v=>v*v))*sum(b.map(v=>v*v)));return den>EPS?sum(a.map((v,i)=>v*b[i]))/den:null;};
return {scope:'SYNTHETIC four-village RDA mechanism; no author data, plot scaling or causal reproduction',row_ids:ids,raw_matrix:matrix,X:x,Y:y,X_means:sx.means,X_sample_sd:sx.sds,Y_means:sy.means,Y_sample_sd:sy.sds,X_standardized:xs,Y_standardized:ys,XTX:xx,XTY:xy,XTX_inverse:inverse,coefficients:coef,fitted_Y:fit,residual_Y:residual,fitted_Y_original_units:fitRaw,residual_Y_original_units:residualRaw,XT_residual:multiply(transpose(xs),residual),fitted_covariance:covariance,constrained_eigenvalues:eigen.values,eigenvectors_columns:eigen.vectors,fitted_axis_scores:axes,observed_axis_scores:observedAxes,X_axis_correlations:xc,Y_axis_correlations:yc,Y_raw_correlation:correlation(y.map(r=>r[0]),y.map(r=>r[1])),Y_coordinate_cosine:cosine(yc[0],yc[1]),X1_YA_raw_correlation:correlation(x.map(r=>r[0]),y.map(r=>r[0])),X1_YA_coordinate_cosine:cosine(xc[0],yc[0]),total_inertia:total,constrained_inertia:constrained,residual_inertia:unconstrained,overall_unadjusted_R2:constrained/total,residual_fraction:unconstrained/total,axis_fraction_of_TOTAL:eigen.values.map(v=>v/total),axis_fraction_of_CONSTRAINED:constrained>EPS?eigen.values.map(v=>v/constrained):null,axis_defined:eigen.values.map(v=>v>EPS),residual_degrees_of_freedom:n-3};}
const API={calculate,standardize,correlation,multiply,eigen2,columns:COLUMNS};if(typeof module!=='undefined'&&module.exports)module.exports=API;if(global)global.PaperRDAModel=API;
})(typeof window!=='undefined'?window:null);
