/* Research-first navigation. Presentation only: original content and every storage key stay intact. */
(()=>{'use strict';
const D=window.PAPER_DATA||{},docs=D.documents||[],byId=new Map(docs.map(d=>[d.id,d])),L=window.PAPER_LIBRARY||{},coverageData=L.coverage?.papers||{},contracts=window.PAPER_CONTRACTS?.contracts||{};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rules=Object.entries(L.presentation||{}).sort((a,b)=>b[0].length-a[0].length);
function explain(s){s=String(s??'');for(const [a,b] of rules)s=s.split(a).join(b);return s;}
const link=(id,label,cls='')=>`<a${cls?` class="${E(cls)}"`:''} href="#/${E(id)}">${E(label||byId.get(id)?.title||id)}</a>`;
const papers=()=>docs.filter(d=>['paper','thesis'].includes(d.type));
function title(t,s){return `<header class="pagehead"><span class="eyebrow">PAPER / RESEARCH WORKSPACE</span><h1>${E(t)}</h1><p>${E(s)}</p></header>`;}
function itemCards(items){return `<div class="grid">${items.map(d=>`<article class="card"><span class="label">${E(explain(d.stage||d.type))}${d.year?' · '+d.year:''}</span><h3>${link(d.id,d.title)}</h3><p>${E(d.summary)}</p>${coverageData[d.id]?`<p class="coverage-inline"><b>核读范围</b> ${E(coverageData[d.id].reading)}</p>`:''}<div class="tags">${(d.tags||[]).map(t=>`<span class="tag">${E(t)}</span>`).join('')}</div>${coverageData[d.id]?link('coverage/'+d.id,'材料与复现缺口 →'):''}</article>`).join('')}</div>`;}
const pathways=[
 ['01','论文论证','现实问题怎样变成研究问题、数据与结论','liang-2022','优先梁政渊、程嘉莉；沿作者真实分析链阅读'],
 ['02','概念与公式','每个变量、单位、算法与假设放回原文','methods','从Pareto、聚类、Q方法到整场守恒'],
 ['03','数据与软件','输入表、连接键、工具版本与运行边界','model-software','区分官方引擎、适配和独立机制示例'],
 ['04','复现记录','对照输入、输出、差异和仍缺的证据','reproduction-records','直接查看解说与脚本，保留研究记录'],
 ['05','博士创新','比较已有研究，形成可检验的研究设计','research-synthesis','连接O1/O2/O3，不以工具堆叠代替贡献']
];
function home(store={}){const last=byId.get(store.last),archived=papers().filter(d=>window.PAPER_SOURCES?.records.find(r=>r.id===d.id)?.bookPath).length;return `<section class="hero research-hero"><span class="eyebrow">从已有研究，到自己的博士体系</span><h1>读清论文的逻辑，<br>连接下一步研究。</h1><p class="lead">围绕梁政渊、程嘉莉等研究，把问题、方法、数据、工具和证据接在一起。快速看全局，也能下钻到原文、公式与运行记录。</p><div class="actions">${link('library','进入论文工作区 →','btn')}${link('research-framework','完整研究框架','btn secondary')}${link('coverage','查看材料覆盖','btn secondary')}</div><div class="research-facts"><span><b>${papers().length}</b>篇主文献</span><span><b>${archived}</b>篇有许可归档原文</span><span><b>3</b>个博士目标</span><span>所有内容自由阅读</span></div><p class="research-footnote">归档数量表示本站可访问的许可原件，不代表全文、图表、附录或结果都已完整核验。</p></section><section class="card study-entry"><h2>${last?'接着上次阅读':'从当前研究问题进入'}</h2><p>${last?'本机上次打开：'+E(last.title)+'。原位置和研究记录继续保留。':'先看研究框架，或直接选择一篇论文；方法、原文与研究迁移可以来回跳转。'}</p><div class="actions">${last?'<button id="continue-reading">返回上次位置</button>':link('liang-2022','梁政渊：从现实系统开始')+link('cheng-2023','程嘉莉：从感知研究开始')}${link('course','七条研究路径 →')}</div></section><div class="sectionhead"><h2>一条可以来回走的研究链</h2></div><nav class="research-chain" aria-label="论文到创新研究路径">${pathways.map(([n,t,d,id,s])=>`<a href="#/${id}"><span>${n}</span><h3>${t}</h3><p>${d}</p><small>${s}</small></a>`).join('')}</nav><section class="research-objectives"><header><span class="eyebrow">与官方 PhD2 目标连接</span><h2>材料最终服务什么研究？</h2><p>以下是研究组织结构；具体案例、数据与方法仍需逐项验证。</p></header><div>${[
 ['O1','异质性与时间变化','系统识别、抽样、指标口径与适应性框架','xu-2024'],['O2','整合生产活动','全农场资源账、地块时空与模型测试','farmdesign-2012'],['O3','养分、水与劳动配置','多目标取舍、偏好、风险与适应性改善','research-synthesis']
 ].map(([n,t,s,id])=>`<article><b>${n}</b><h3>${t}</h3><p>${s}</p>${link(id,'打开研究线索 →')}</article>`).join('')}</div><p>${link('topic6-requirements','原课题目标与边界') } · ${link('hainan-map','海南迁移') }</p></section><div class="sectionhead"><h2>优先研究档案</h2>${link('library','查看全部22篇 →')}</div>${itemCards(['liang-2022','liang-2023','farmsteps-2026','cheng-2023','cheng-2025','xu-2024'].map(id=>byId.get(id)))}<section class="notice"><b>新增：句子旁的上下文解释与可交互走读。</b> ${link('interactive-research-guide','从哪开始、怎样看每一步 →')} ${link('liang-indicator-audit','七指标公式、来源标记与完整代入 →')} ${link('liang-exemplar-transfer','从优秀案例到PhD2研究设计 →')} ${link('explanation-roadmap','全站具体缺口与深化路线 →')} 22篇已有解释与方法账本保留；合成结果与原作者复现分别标识。${link('coverage','打开证据覆盖台账 →')}</section>`;}
function library(type){const method=type==='methods',arr=docs.filter(d=>method?d.type==='method':['paper','thesis'].includes(d.type));return title(method?'概念与方法':'论文工作区',method?'概念定义 → 符号与量纲 → 解说示例 → 使用该方法的论文。按当前问题自由查阅。':'按作者与主题查找研究。每篇保留论证链、原文定位、输入输出、方法账本与研究迁移。')+`<div class="actions">${link(method?'glossary':'coverage',method?'中英文术语词典':'22篇覆盖与证据缺口')}${link(method?'reproduction-records':'method-ledgers',method?'完整推导与运行示例':'逐篇方法账本')}${link('discover','检索与导入自己的论文')}</div><div class="filters"><button data-filter="all" class="active" aria-pressed="true">全部</button>${(method?['基础','建模','调查','数据']:['梁政渊','程嘉莉','徐展','博士','模型']).map(x=>`<button data-filter="${x}" aria-pressed="false">${x}</button>`).join('')}</div><p id="catalog-status" role="status">全部 · ${arr.length}条</p><div id="catalog">${itemCards(arr)}</div>`;}
function coverage(){return title('22篇内容覆盖与证据缺口','状态描述材料和核验范围，不评价读者；可取得原文、已核读正文、完成结果复现是不同的事情。')+`<p class="notice">${E(L.coverage?.basis)} 更新日期：${E(L.coverage?.date)}。未登记并不等于不存在，取得材料后再更新。${link('corrections','核验与勘误')}</p><div class="coverage-list">${papers().map(d=>{const c=coverageData[d.id],r=window.PAPER_SOURCES?.records.find(r=>r.id===d.id);return `<article class="card coverage-card" id="${d.id}"><h2>${link(d.id,d.title)}</h2><dl><dt>原件获取</dt><dd>${r?.bookPath?'许可原文已归档，可在站内查阅':'公开站未归档全文；查看合法来源或本机导入'}</dd>${[['已核读范围',c.reading],['附录与逐图核对',c.appendix],['作者数据',c.data],['作者代码',c.code],['结果复现',c.reproduction]].map(([a,b])=>`<dt>${E(a)}</dt><dd>${E(b)}</dd>`).join('')}</dl><div class="actions">${link(d.id,'论文论证与方法')}${link(d.id+'/method-contract','数据、工具与缺口')}${link('original/'+d.id,'原文获取状态')}</div></article>`;}).join('')}</div>`;}
function work(){return title('我的工作','继续阅读、整理证据与研究备忘。已有本机记录、批注、阅读位置和旧版标记保留；没有成绩或必填任务。')+`<div class="grid">${[
 ['notes','笔记与备份','整篇研究笔记、旧版记录及JSON导入/导出'],['annotations','划线批注与便签','回到原文段落、公式与图表的位置'],['research-feedback','所有输入与待回应','分节备注、方法账本、工作表和未解决问题'],['research-studio','研究设计工作台','把文献解释转成研究问题、变量和验证安排'],['research-decisions','集中决策面板','集中查看尚待判断的研究选择'],['my-library','个人文献库','合法导入的原文、元数据和个人工作表'],['sync','私有同步状态','查看真实检查点和当前设备状态'],['offline','离线与下载','保存公开资料、脚本和独立阅读备份']
 ].map(([id,t,s])=>`<article class="card"><h2>${link(id,t)}</h2><p>${s}</p></article>`).join('')}</div><p class="notice">未获云端确认的数据仍只在当前设备。网站更新不会等同于私人数据备份；请保留可恢复的备份。</p>`;}
function mount(){const id=decodeURIComponent(location.hash.split('/')[1]||''),root=document.querySelector('#view .reader'),d=byId.get(id),c=coverageData[id],contract=contracts[id];if(!root||!c||root.querySelector('.research-reading-layers'))return;const box=document.createElement('section');box.className='research-reading-layers';box.id='research-overview';box.innerHTML=`<span class="eyebrow">研究档案 / 自由选择阅读深度</span><h2>先抓住问题，再下钻证据</h2><p>${E(contract?.question||d.summary)}</p><nav aria-label="三层研究阅读"><a href="#/${E(id)}/${window.PAPER_STUDY?.frameworks?.[id]?'paper-framework':'s0'}"><b>01 快速总图</b><span>问题、对象、分析链与产出</span></a><a href="#/${E(id)}/method-contract"><b>02 方法拆解</b><span>输入、计算、输出与工具</span></a><a href="#/${E(id)}/research-evidence"><b>03 证据与复现</b><span>原文定位、材料状态与运行记录</span></a></nav><p class="coverage-inline"><b>实际核读范围：</b>${E(c.reading)}</p><div class="actions">${link('coverage/'+id,'原文 / 附录 / 数据 / 代码 / 复现状态')}${link('research-synthesis','连接博士创新 →')}</div>`;root.querySelector('.articlehead')?.after(box);const evidence=root.querySelector('.research-bridge')||root.querySelector('#self-test')||root.querySelector('#method-contract');if(evidence&&evidence.id!=='self-test'&&evidence.id!=='method-contract')evidence.id='research-evidence';else if(evidence){const anchor=document.createElement('span');anchor.id='research-evidence';evidence.before(anchor);}}
window.PaperLibrary={home,library,coverage,work,mount,explain,cards:itemCards};
})();
