/* Research-reader v5.3: original evidence stays immutable; all personal writing stays local/private. */
(()=>{'use strict';
const R=window.PAPER_RESEARCH||{},D=window.PAPER_DATA||{documents:[]},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],KEY='paper-lab-learning-v1';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route=()=>{try{return decodeURIComponent(location.hash.replace(/^#\/?/,''));}catch{return '';}};
const docID=()=>route().split('/')[0],docs=new Map(D.documents.map(d=>[d.id,d])),pending=new Map(),urls=new Set();let applying=false,scheduled=false,dashboardEpoch=0;
const norm=s=>String(s||'').normalize('NFKC').replace(/\u00ad/g,'').replace(/([a-z])-\s*\n\s*([a-z])/g,'$1$2').replace(/\s+/g,' ').trim();
const safePath=s=>typeof s==='string'&&s.startsWith('library/')&&!s.split('/').includes('..')&&!/[\\\0]/.test(s)?s:'';
function state(){let x;try{x=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{throw Error('现有笔记存储无法解析，未覆盖。请先保留备份。');}if(!x||typeof x!=='object'||Array.isArray(x))throw Error('现有笔记结构异常，未覆盖。');x.notes||={};return x;}
function mergeText(base,local,remote){if(local===remote||remote===base)return local;if(local===base)return remote;if(!remote)return local;if(!local)return remote;if(local.includes(remote))return local;if(remote.includes(local))return remote;return local+'\n\n【并发修改的另一版本，请核对】\n'+remote;}
function noteKey(id,anchor){return 'research::'+id+'::'+anchor;}
function noteBox(id,anchor,label='我的需求 / 备注',open=false){
const key=noteKey(id,anchor),box=document.createElement('details');box.className='research-note-box';box.dataset.noteKey=key;box.setAttribute('data-no-terms','');let original='';try{original=state().notes[key]||'';}catch{}
box.open=open||!!original;box.innerHTML='<summary>'+E(label)+' <span class="research-save-status"></span></summary><textarea rows="2" maxlength="20000" aria-label="'+E(label)+'" placeholder="写下不明白的细节、研究想法或修改要求。自动保存，不需要点保存。"></textarea><small class="research-cloud-status"></small>';
const field=$('textarea',box),status=$('.research-save-status',box);field.value=original;field._researchBase=original;
const save=()=>{try{const x=state(),remote=String(x.notes[key]||''),value=mergeText(field._researchBase,field.value,remote);x.notes[key]=value;localStorage.setItem(KEY,JSON.stringify(x));field._researchBase=value;if(value!==field.value){const p=field.selectionStart;field.value=value;field.setSelectionRange(p,p);}status.textContent='已存本机';box.dataset.saved='true';pending.delete(key);window.PaperSync?.changed('learning');document.dispatchEvent(new CustomEvent('paper-research-saved',{detail:{key}}));cloudStatus(box);return true;}catch(e){status.textContent='未保存：'+e.message;box.dataset.saved='false';pending.set(key,{field,save});return false;}};
field.addEventListener('input',()=>{pending.set(key,{field,save});save();});field.addEventListener('compositionend',save);field.addEventListener('blur',save);cloudStatus(box);return box;
}
function cloudStatus(root=document){const s=window.PaperSync?.status?.();for(const el of $$('.research-cloud-status',root)){el.textContent=s?.state==='synced'?'GitHub已确认最近检查点；本框后续修改会继续排队。':s?.connected?'本机保存后自动排队同步；待GitHub确认。':'目前仅本机；免手填后台未接通，未显示云端成功。';}}
function phaseOf(title){if(/指标|indicator|性能|绩效|performance|营养|投入产出|参数|MCI|分母/i.test(title))return 'indicator';if(/样本|sampling|数据|survey|问卷|调查|感知|Q方法|Q-set/i.test(title))return 'data';if(/结果|局限|结论|限制|外推|limitations|results|风险|验收|情景/i.test(title))return 'inference';if(/模型|方法|method|算法|公式|聚类|PCA|Pareto|ROTAT|建模|模块/i.test(title))return 'method';return 'question';}
function lens(id,anchor,title,paper){const phase=R.phases?.[phaseOf(title)]||{},box=document.createElement('details');box.className='research-lens';box.innerHTML='<summary>研究导师标注 · '+E(phase.label||'理解与迁移')+' <small>注意 → 掌握 → 启发 → 构思</small></summary><p class="research-boundary">以下为教学解释和候选研究建议，不替作者补写结论，也不替导师确定研究方向。</p><div class="research-four"></div>';
const area=$('.research-four',box);for(const [key,label] of [['notice','特别注意'],['mastery','掌握到什么程度'],['insight','对博士的启发'],['design','怎样构思研究']]){const item=document.createElement('div');item.className='research-guidance';item.innerHTML='<h4>'+label+'</h4><p>'+E(phase[key]||'')+'</p>'+(paper?.[key]?'<p class="research-specific">本篇：'+E(paper[key])+'</p>':'');item.append(noteBox(id,anchor+'-'+key,'对此标注的备注'));area.append(item);}return box;}
async function readDB(name,store){return new Promise((ok,no)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>{const list={'paper-lab-reader-v2':['books','files','annotations','positions'],'paper-workspace-v4':['references','workbooks','terms'],'paper-comfort-v5':['tags','drafts','conflicts'],'paper-translations-v3':['translations']}[name]||[];for(const s of list)if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:'id'});};r.onerror=()=>no(r.error);r.onsuccess=()=>{const db=r.result;if(!db.objectStoreNames.contains(store)){db.close();ok([]);return;}const tx=db.transaction(store,'readonly'),q=tx.objectStore(store).getAll();q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error);tx.oncomplete=()=>db.close();};});}
async function getLocalFile(id){const db=await new Promise((ok,no)=>{const q=indexedDB.open('paper-lab-reader-v2',1);q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error);});try{return await new Promise((ok,no)=>{if(!db.objectStoreNames.contains('files')){ok(null);return;}const q=db.transaction('files').objectStore('files').get(id);q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error);});}finally{db.close();}}
async function originalBook(id){if(window.PaperReader?.loadBook)return window.PaperReader.loadBook(id);const local=(await readDB('paper-lab-reader-v2','books')).filter(b=>b.id===id||b.lessonId===id);if(local.length===1)return local[0];const rec=window.PAPER_SOURCES?.records.find(r=>r.id===id);if(!rec?.bookPath)return null;const p=safePath(rec.bookPath);if(!p)throw Error('原文路径不安全');const response=await fetch(p);if(!response.ok)throw Error('原文未缓存或暂不可读取');return response.json();}
function jumpHref(book,block){return '#/original/'+encodeURIComponent(book.id)+'/'+encodeURIComponent(block);}
async function pageFigure(book,page,root){if(!page.snapshot)return;const fig=document.createElement('figure');fig.className='research-source-figure';const image=document.createElement('img');image.loading='lazy';image.alt=book.title+' · 原文第'+page.number+'页完整图文';
if(page.local||book.local){const f=await getLocalFile(page.snapshot);if(!f?.blob){const p=document.createElement('p');p.textContent='该原页图片尚未在本机恢复；原文文字与已保存笔记不变。';root.append(p);return;}const u=URL.createObjectURL(f.blob);urls.add(u);image.src=u;}else{const p=safePath(page.snapshot);if(!p)return;image.src=p;}
image.onerror=()=>{const warn=document.createElement('p');warn.className='notice';warn.textContent='原页图片尚未缓存，联网后完整缓存原文即可。';fig.append(warn);};fig.append(image);const cap=document.createElement('figcaption');cap.textContent='来源：'+(book.citation||book.title)+'；原文第'+page.number+'页。原始页面完整保留；不是重新绘制的图。';fig.append(cap);const a=document.createElement('a');a.href=jumpHref(book,'page-'+page.number);a.textContent='在原文中打开本页，之后可返回此处 →';fig.append(a);root.append(fig);}
function evidence(id,source,spec={}){const panel=document.createElement('details');panel.className='research-evidence';panel.dataset.source=source;panel.innerHTML='<summary>'+E(spec.title||'就地查看原文、公式与图表')+'</summary><div class="evidence-body"><p>英文证据从已存原件读取，不由带读重新生成。带读翻译和研究建议与它分开。</p><div class="evidence-content"></div></div>';
let loaded=false;panel.addEventListener('toggle',async()=>{if(!panel.open||loaded)return;loaded=true;const root=$('.evidence-content',panel);root.textContent='正在读取原文…';try{const book=await originalBook(source);if(!book){root.innerHTML='<p>此设备尚未取得/恢复该篇完整原件，不能根据摘要生成证据。已公开许可原件可完整缓存；私有原件需合法导入或恢复。</p><a href="#/original/'+E(source)+'">查看原件状态</a>';return;}root.textContent='';const entries=book.pages.flatMap(p=>p.blocks.filter(b=>b.text).map(b=>({...b,page:p.number}))),byid=new Map(entries.map(b=>[b.id,b]));let selected=[];
if(spec.blocks?.length){for(const bid of spec.blocks){const b=byid.get(bid);if(b)selected.push(b);else{const p=document.createElement('p');p.className='notice';p.textContent='已校对的段落锚点在此版本中未找到：'+bid+'。未自动换成其他段落，请对照页图。';root.append(p);}}}
else if(spec.query){const q=norm(spec.query).toLowerCase();selected=entries.filter(b=>norm(b.text).toLowerCase().includes(q)&&b.text.length>60).slice(0,spec.max||5);const p=document.createElement('p');p.className='research-boundary';p.textContent='以下按“'+spec.query+'”定位原文，属于检索命中，不表示已经人工判定每段都支持本节所有主张。';root.append(p);}
for(const b of selected){const box=document.createElement('article');box.className='research-excerpt';const p=document.createElement('p');p.lang='en';p.textContent=b.text;box.append(p);const a=document.createElement('a');a.href=jumpHref(book,b.id);a.textContent='原文第'+b.page+'页 · '+b.id+' ↗';box.append(a);box.append(noteBox(id,'source-'+b.id,'对这段原文的疑问'));root.append(box);}
const captionPages=[];for(const label of spec.figureLabels||[]){const m=label.match(/^(Fig\.?|Table)\s*(\d+)$/i);if(!m)continue;const re=new RegExp('^'+(m[1].toLowerCase().startsWith('fig')?'Fig\\.?':'Table')+'\\s*'+m[2]+'(?:[. :]|$)','i');for(const b of entries)if(re.test(norm(b.text)))captionPages.push(b.page);}
const numbers=[...new Set([...(spec.pages?.length?spec.pages:selected.map(b=>b.page)),...captionPages])];if(!selected.length&&!numbers.length){root.append(document.createTextNode('未找到对应段落。可在下方输入原文关键词继续定位；不会补写不存在的原句。'));}
for(const n of numbers){const p=book.pages.find(p=>p.number===n);if(!p)continue;const details=document.createElement('details');details.className='evidence-page';details.innerHTML='<summary>原文第'+n+'页：查看完整图、表、公式与上下文</summary>';const target=document.createElement('div');details.append(target);let drawn=false;details.addEventListener('toggle',()=>{if(details.open&&!drawn){drawn=true;pageFigure(book,p,target).catch(e=>target.textContent=e.message);}});root.append(details);}
if(window.PaperStudy?.terms)window.PaperStudy.terms(root);
}catch(e){loaded=false;root.textContent='未读取原文：'+e.message+'。关闭后可重试；未替换为摘要。';}});return panel;}
function searchEvidence(id,source){const box=document.createElement('details');box.className='research-evidence evidence-search';box.innerHTML='<summary>在这篇原文中继续定位证据</summary><form><input aria-label="原文证据关键词" placeholder="输入英文方法、变量或表号，例如 Table 1"><button>定位</button></form><div class="evidence-results"></div>';const form=$('form',box);form.onsubmit=e=>{e.preventDefault();const q=$('input',box).value.trim();if(!q)return;const panel=evidence(id,source,{title:'原文命中：'+q,query:q,max:8}),root=$('.evidence-results',box);root.replaceChildren(panel);panel.open=true;};return box;}
function indicatorTable(root){const box=document.createElement('section');box.id='seven-indicators';box.className='research-indicator-table';box.innerHTML='<span class="eyebrow">完整指标矩阵 / 原文§2.4</span><h2>三域、七项：先把全部选择放在同一张表里</h2><p>下表为原文定义的教学整理，不将其改称作者使用了Delphi/AHP筛选。点开每一行，可看原句、计算边界、图式与自己的备注。</p>';
for(const row of R.indicatorRows||[]){const d=document.createElement('details');d.className='indicator-row';d.dataset.indicator=row.id;d.innerHTML='<summary><b>'+E(row.name)+'</b><span>'+E(row.unit)+'</span></summary><dl>'+[['域与方向',row.domain+' · '+row.direction],['计算需要什么',row.inputs],['为何选择',row.rationale],['边界与易错点',row.boundary]].map(([a,b])=>'<dt>'+E(a)+'</dt><dd>'+E(b)+'</dd>').join('')+'</dl><a href="#/liang-indicator-audit/s'+row.section+'">进入完整逐项讲解 →</a>';d.append(evidence('liang-indicator-audit','liang-2022',{title:'对应原文、公式与完整页图',blocks:row.blocks,pages:row.pages}));d.append(noteBox('liang-indicator-audit','indicator-'+row.id,'这项指标的备注'));box.append(d);}root.querySelector('.articlehead')?.after(box);}
function samplingGrid(root){const box=document.createElement('section');box.className='sampling-grid-section';box.id='sampling-method-cards';box.innerHTML='<h2>方法卡片：按任务和约束检索</h2><input class="sampling-filter" type="search" aria-label="检索样本选取方法" placeholder="例如 概率、空间、回访、最大差异"><p class="research-boundary">32张方法/设计卡片覆盖主要方法族；部分专门领域仍只列扩展入口，不冒称穷尽全部方法。</p><div class="sampling-cards"></div>';const draw=q=>{const area=$('.sampling-cards',box);area.textContent='';for(const [name,type,id,desc] of R.samplingCards||[]){if(q&&!([name,type,desc].join(' ')).toLowerCase().includes(q.toLowerCase()))continue;const card=document.createElement('div');card.className='sampling-card';card.innerHTML='<small>'+E(type)+'</small><h3><a href="#/'+E(id)+'">'+E(name)+'</a></h3><p>'+E(desc)+'</p>';card.append(noteBox('sampling-library','method-'+name,'对这个方法的备注'));area.append(card);}};$('.sampling-filter',box).oninput=e=>draw(e.target.value);draw('');root.querySelector('.articlehead')?.after(box);}
async function collectInputs(){const rows=[];let learning;try{learning=state();}catch(e){return [{id:'error',kind:'读取失败',text:e.message,href:'#/research-feedback'}];}
for(const [key,text] of Object.entries(learning.notes||{})){if(!String(text).trim())continue;const a=key.split('::'),special=a[0]==='research',id=special?a[1]:key,anchor=special?a.slice(2).join('::'):'';rows.push({id:'learning:'+key,kind:special?'研究小框':'整篇笔记',text:String(text),title:docs.get(id)?.title||id,href:special&&id==='term'?'#/glossary':special&&id.startsWith('original-')?'#/original/'+id.slice(9)+'/'+anchor:anchor.startsWith('source-')&&R.papers?.[id]?'#/original/'+R.papers[id].source+'/'+anchor.slice(7):'#/'+id+(anchor.match(/^s\d+/)?'/'+anchor.match(/^s\d+/)[0]:'')});}
const groups=[['paper-lab-reader-v2','annotations','划线/批注/便签'],['paper-workspace-v4','workbooks','阅读工作表'],['paper-workspace-v4','terms','自定义术语'],['paper-workspace-v4','references','文献元数据'],['paper-comfort-v5','tags','自定义标签'],['paper-comfort-v5','drafts','草稿'],['paper-comfort-v5','conflicts','冲突待核'],['paper-translations-v3','translations','个人校订译文']];
for(const [db,store,kind] of groups){let records;try{records=await readDB(db,store);}catch(e){rows.push({id:db+'/'+store,kind:'读取失败',text:e.message,href:'#/research-feedback'});continue;}for(const v of records){if(store==='translations'&&!(v.reviewed||v.editedAt||v.corrected||['reviewed','edited','human','corrected'].includes(v.status)||v.mode==='edited'))continue;let text='';if(store==='annotations')text=[v.comment,v.quote].filter(Boolean).join('\n原文锚定：');else if(store==='workbooks')text=Object.entries(v.values||{}).filter(([,x])=>String(x||'').trim()).map(([k,x])=>k+'：'+x).join('\n\n');else if(store==='terms')text=[v.definition,v.explanation,v.example,v.boundary].filter(Boolean).join('\n');else if(store==='tags')text=[v.label,v.text,v.example,v.href].filter(Boolean).join('\n');else if(store==='references')text=[v.title,v.doi,v.notes].filter(Boolean).join('\n');else if(store==='drafts')text=v.text||v.comment||v.value||JSON.stringify(v);else if(store==='conflicts'){if(v.resolved)continue;text=JSON.stringify(v,null,2);}else text=v.translation||v.text||v.value||JSON.stringify(v);if(!String(text).trim())continue;const doc=v.docId||v.bookId||v.id,block=v.segments?.[0]?.block||v.block||'';rows.push({id:db+'/'+store+'/'+v.id,kind,title:v.title||v.label||doc,text:String(text),at:v.updatedAt||v.createdAt||v.editedAt||null,href:store==='annotations'?(doc.startsWith('lesson:')?'#/'+doc.slice(7):doc==='global'?'#/annotations':'#/original/'+doc+(block?'/'+block:'')):store==='workbooks'?'#/workbook/'+v.id:store==='translations'?'#/original/'+(v.docId||v.bookId||''):'#/'+(store==='tags'?'annotations':store==='terms'?'glossary':store==='drafts'?'annotations':store==='conflicts'?'sync':'my-library')});}}
return rows;}
async function dashboard(root){const epoch=++dashboardEpoch,box=document.createElement('section');box.id='research-input-dashboard';box.innerHTML='<h2>本设备可见的全部输入</h2><div class="research-dashboard-tools"><input type="search" aria-label="搜索全部个人输入" placeholder="搜索备注、原文位置、需求"><button type="button" class="refresh-inputs">重新读取所有位置</button><button type="button" class="export-inputs">导出审阅包</button></div><p class="research-input-status" role="status">正在读取…</p><div class="research-input-list"></div>';root.querySelector('.articlehead')?.after(box);let rows=[];
const draw=()=>{const q=$('input',box).value.toLowerCase(),list=$('.research-input-list',box);list.textContent='';const hits=rows.filter(r=>(r.kind+' '+r.title+' '+r.text).toLowerCase().includes(q));$('.research-input-status',box).textContent='可读取 '+rows.length+' 条，当前显示 '+hits.length+' 条。只包含本机已存/已恢复数据；尚未同步的其他设备不可见。';for(const r of hits){const d=document.createElement('details');d.className='research-input-item';d.innerHTML='<summary><small>'+E(r.kind)+'</small> '+E(r.title||r.id)+'</summary><pre>'+E(r.text)+'</pre><a href="'+E(r.href)+'">返回输入位置 →</a>';list.append(d);}};
const refresh=async()=>{rows=await collectInputs();if(epoch!==dashboardEpoch||!box.isConnected)return;draw();};$('.refresh-inputs',box).onclick=refresh;$('input',box).oninput=draw;$('.export-inputs',box).onclick=()=>{const blob=new Blob([JSON.stringify({schema:'paper.user-input-review.v53',generatedAt:new Date().toISOString(),cloud:window.PaperSync?.status?.().confirmedAt||null,records:rows},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='Paper-private-writing-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);};await refresh();}
const mountedResearch=new Map();
function enhance(){scheduled=false;if(applying)return;applying=true;try{const id=docID(),root=$('#view .reader');if(root&&docs.has(id)&&!root.dataset.researchV53){root.dataset.researchV53='true';root.dataset.researchDoc=id;const cached=mountedResearch.get(id);if(cached&&id!=='research-feedback'){
 root.querySelector('.articlehead')?.after(...cached.top);
 for(const [anchor,node] of cached.sections)root.querySelector('#'+anchor)?.append(node);
 for(const box of $$('.research-note-box',root)){const f=$('textarea',box);try{const value=state().notes[box.dataset.noteKey]||'';if(document.activeElement!==f){f.value=value;f._researchBase=value;}}catch{}}
 cloudStatus(root);
}else{const d=docs.get(id),p=R.papers?.[id];if(p){const intro=document.createElement('section');intro.className='research-bridge';intro.id='research-bridge';intro.innerHTML='<span class="eyebrow">研究导师视角 / PhD2</span><h2>这篇论文怎样进入你的研究设计</h2><p>'+E(p.question)+'</p><div class="source-links"><a href="#/research-studio">研究工作台</a><a href="#/sampling-library">样本选取专题</a>'+(p.link?'<a href="#/'+E(p.link)+'">进入本篇详细专题 →</a>':'')+'</div>';intro.append(lens(id,'paper-lens',d.title,p));for(const spec of p.evidence||[])intro.append(evidence(id,p.source,spec));intro.append(searchEvidence(id,p.source));root.querySelector('.articlehead')?.after(intro);}
for(const [i,s] of d.sections.entries()){const el=root.querySelector('#s'+i);if(!el)continue;const group=document.createElement('div');group.className='research-section-tools';group.append(noteBox(id,'s'+i,'本节：我的需求 / 笔记'));if(p&&[0,1,2,3,d.sections.length-1].includes(i))group.prepend(lens(id,'s'+i,s[0],p));if(id==='liang-indicator-audit'){const specs=R.papers[id].evidence;const index=i<=1?0:i>=2&&i<=8?i-1:i===9?8:-1;if(index>=0)group.prepend(evidence(id,'liang-2022',specs[index]));}el.append(group);}
if(id==='liang-indicator-audit')indicatorTable(root);if(id==='sampling-library')samplingGrid(root);if(id==='research-feedback')dashboard(root).catch(e=>{root.append(document.createTextNode('读取个人输入失败：'+e.message));});
 if(id!=='research-feedback'){mountedResearch.set(id,{top:$$(':scope > .research-bridge,:scope > .research-indicator-table,:scope > .sampling-grid-section',root),sections:$$(':scope > section > .research-section-tools',root).map(n=>[n.parentElement.id,n])});if(mountedResearch.size>10)mountedResearch.delete(mountedResearch.keys().next().value);}
 }}
const original=$('#view .original-reader');if(original&&!original.dataset.researchV53){original.dataset.researchV53='true';const parts=route().split('/'),source=parts[1],dock=document.createElement('details');dock.className='original-research-dock';dock.innerHTML='<summary>研究札记 / 当前原文位置</summary><p>把这段对选题、指标或调研的疑问记下来。</p>';const holder=document.createElement('div');dock.append(holder);dock.addEventListener('toggle',()=>{if(!dock.open)return;const visible=$$('[data-block]',original).find(n=>n.getBoundingClientRect().bottom>140&&n.getBoundingClientRect().top<innerHeight);const anchor=visible?.id||parts[2]||'overview';if(holder.dataset.anchor===anchor)return;holder.dataset.anchor=anchor;holder.replaceChildren(noteBox('original-'+source,anchor,'原文研究备注 · '+anchor,true));});original.querySelector('.reader-toolbar')?.after(dock);}
const pop=$('#study-term-popover');if(pop&&!pop.dataset.researchV53){const selected=$('[data-study-term][aria-expanded="true"]');if(selected){pop.dataset.researchV53='true';pop.append(noteBox('term',selected.dataset.studyTerm,'这个术语：我的疑问'));}}
}finally{applying=false;}}
function schedule(){if(scheduled)return;scheduled=true;setTimeout(enhance,80);}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});document.addEventListener('paper-sync-status',()=>cloudStatus());addEventListener('paper-sync-applied',()=>{for(const box of $$('.research-note-box')){const field=$('textarea',box);if(document.activeElement===field)continue;try{const value=state().notes[box.dataset.noteKey]||'';field.value=value;field._researchBase=value;}catch{}}});addEventListener('storage',e=>{if(e.key===KEY)dispatchEvent(new Event('paper-sync-applied'));});addEventListener('pagehide',()=>{for(const x of pending.values())x.save();});
window.PaperResearch={version:'5.3.0',enhance,noteBox,mergeText,collectInputs,originalBook,noteKey,flush:()=>{for(const x of pending.values())x.save();},hasUnsaved:()=>pending.size>0};schedule();
})();
