/* Paper Study v3. Source text remains immutable; all personal translation imports stay on device. */
(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S=window.PAPER_STUDY||{glossary:{terms:[]},frameworks:{papers:{}}};
let current=null,layout=null,translation=null,popup=null,dbPromise,ticket=0;
const cache=new Map(),termById=new Map((S.glossary?.terms||[]).map(t=>[t.id,t]));
const safePath=p=>typeof p==='string'&&!/^(?:[a-z]+:|\/)/i.test(p)&&!p.split('/').includes('..')?p:'';
const norm=s=>String(s||'').replace(/\u00ad\s*/g,'').replace(/\s+/g,' ').trim();
const hash=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');
function visible(){try{return localStorage.getItem('paper-study-zh-visible')!=='0';}catch{return true;}}
function saveVisible(v){try{localStorage.setItem('paper-study-zh-visible',v?'1':'0');}catch{}}
function db(){return dbPromise||(dbPromise=new Promise((ok,no)=>{const q=indexedDB.open('paper-study-v3',1);q.onupgradeneeded=()=>q.result.createObjectStore('translations',{keyPath:'id'});q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error);}));}
async function io(method,value){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction('translations',method==='get'?'readonly':'readwrite'),r=tx.objectStore('translations')[method](value);let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>ok(result);tx.onerror=()=>no(tx.error);tx.onabort=()=>no(tx.error);});}
async function jsonAsset(path){if(!safePath(path))return null;if(cache.has(path))return cache.get(path);const r=await fetch(path);if(!r.ok)throw Error('资料尚未缓存：'+path);const x=await r.json();cache.set(path,x);return x;}
async function loadOriginal(book){const mine=++ticket;current=book;layout=null;translation=null;const li=S.formulaIndex?.records?.find(x=>x.sourceHash===book.sourceHash),ti=S.translationIndex?.records?.find(x=>x.sourceHash===book.sourceHash);const results=await Promise.allSettled([li?jsonAsset(li.path):null,io('get',book.sourceHash),ti?jsonAsset(ti.path):null]);if(mine!==ticket)return;
const l=results[0].status==='fulfilled'?results[0].value:null,local=results[1].status==='fulfilled'?results[1].value?.payload:null,pub=results[2].status==='fulfilled'?results[2].value:null;
if(l?.sourceHash===book.sourceHash)layout=l;const t=local||pub;if(t?.sourceHash===book.sourceHash){translation={...t,blocks:{}};const byHash=new Map(Object.values(t.blocks).map(v=>[v.sourceTextHash,v]));await Promise.all(book.pages.flatMap(p=>p.blocks).filter(b=>b.text).map(async b=>{const h=await hash(norm(b.text)),v=t.blocks[b.id]||byHash.get(h);if(v?.sourceTextHash===h)translation.blocks[b.id]=v;}));if(!Object.keys(translation.blocks).length)translation=null;}
}
function originalTextHTML(b,tag){return `<${tag} class="original-block ${tag==='h2'?'original-heading':''}" id="${E(b.id)}" data-block="${E(b.id)}" data-language="en">${E(String(b.text||'').replace(/\s+/g,' ').trim())}</${tag}>`;}
function chinese(b){const t=translation?.blocks?.[b.id];if(!t)return '';if(t.status==='verbatim-symbols')return `<div class="paragraph-zh symbolic-translation" lang="zh-CN"><span>符号、数字或标识按原文保留，不另行意译。</span></div>`;return `<div class="paragraph-zh" lang="zh-CN" data-translation-for="${E(b.id)}"><div class="translation-label">中文对照 · ${t.status==='reviewed'?'已对照原段核译':'机器初译'}${t.flags?.length?' <span title="自动检查提示本段数字或语言需对照英文">请核对原文</span>':''}</div><p id="${E(b.id)}--zh" data-block="${E(b.id)}--zh" data-language="zh-CN">${E(t.zh)}</p></div>`;}
function blockHTML(b,book){if(!b.text)return null;const eqid=layout?.blockMap?.[b.id],eq=eqid&&layout.equations.find(e=>e.id===eqid);
if(eq){if(eq.first!==b.id)return '';const members=book.pages.flatMap(p=>p.blocks).filter(x=>eq.members.includes(x.id));return `<figure class="formula-display" id="${E(eq.id)}" data-equation="${E(eq.label)}"><div class="formula-scroll">${eq.mathML||`<img class="formula-image" src="${E(safePath(eq.path))}" alt="原文公式 (${E(eq.label)})，从原始文件完整裁取">`}<span class="equation-number">(${E(eq.label)})</span></div>${eq.gloss?`<figcaption class="paragraph-zh formula-gloss" lang="zh-CN">式义：${E(eq.gloss)}</figcaption>`:''}<div class="formula-actions"><button data-formula-proof="${E(safePath(eq.path))}">核对原式</button><button data-image-note="${E(eq.id)}">公式便签</button></div><details class="formula-raw"><summary>原始提取文字与旧批注定位</summary>${members.map(x=>originalTextHTML(x,'p')+chinese(x)).join('')}</details></figure>`;}
const heading=b.kind==='heading'&&(!layout||layout.sectionHeadingIds.includes(b.id)||norm(b.text)===norm(book.title));const html=`<div class="bilingual-pair" data-pair="${E(b.id)}">${originalTextHTML(b,heading?'h2':'p')}${chinese(b)}</div>`;
return layout?.classification?.[b.id]==='running-metadata'?`<details class="running-metadata"><summary>出版信息 / 原页页眉页脚</summary>${html}</details>`:html;
}
function anchor(){const v=$('#original-viewport');if(!v)return null;return $$('[data-block]',v).find(x=>{const r=x.getBoundingClientRect(),b=v.getBoundingClientRect();return r.width&&r.height&&r.bottom>Math.max(b.top,100)&&r.top<innerHeight&&r.right>b.left&&r.left<b.right;})?.id;}
function reveal(id){const e=document.getElementById(id);if(!e)return;for(let p=e.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;const v=$('#original-viewport');if(v?.classList.contains('paged')){const s=($('#original-text')?.clientWidth||1)+32;v.scrollLeft=Math.floor((e.getBoundingClientRect().left-v.getBoundingClientRect().left+v.scrollLeft-parseFloat(getComputedStyle(v).paddingLeft)+2)/s)*s;v.dispatchEvent(new Event('scroll'));}else e.scrollIntoView({block:'start',behavior:'instant'});}
function enhanceOriginal(book){const root=$('.original-reader');if(!root)return;root.dataset.studyVersion='3';root.classList.toggle('zh-off',!visible());$('#study-side-controls')?.remove();const controls=document.createElement('aside');controls.id='study-side-controls';controls.setAttribute('aria-label','原文对照阅读开关');controls.innerHTML=`<button id="zh-toggle" aria-pressed="${visible()}" title="开启或关闭每段下面的中文">中<span>${visible()?'开':'关'}</span></button><button id="zh-import" title="导入本机中文对照包">导入<br>译文</button>`;root.append(controls);
$('#zh-toggle').onclick=()=>{const a=anchor(),v=!visible();saveVisible(v);root.classList.toggle('zh-off',!v);$('#zh-toggle').setAttribute('aria-pressed',String(v));$('#zh-toggle span').textContent=v?'开':'关';requestAnimationFrame(()=>{if(a)reveal(a);window.dispatchEvent(new Event('resize'));});};$('#zh-import').onclick=chooseTranslation;
const c=translation?Object.values(translation.blocks):[];const info=document.createElement('div');info.className='bilingual-status';info.id='bilingual-status';info.dataset.coverage=String(c.length);info.textContent=translation?`逐段中文已加载：${c.filter(x=>x.status!=='verbatim-symbols').length}段；英文原文始终保留。中文是阅读辅助初译，数字、单位和方法表述请对照英文。右侧“中”可开关。`:'本篇尚未载入与原件匹配的中文包。许可限制的译文请用右侧“导入译文”存入本机；不会上传。已公开译文若断网未载入，请先完整缓存。';$('.reader-toolbar').before(info);
$$('[data-formula-proof]',root).forEach(btn=>btn.onclick=()=>{const d=document.createElement('dialog');d.className='image-dialog formula-proof-dialog';d.innerHTML='<button type="button">关闭原式</button><img alt="原始公式完整裁图">';$('img',d).src=btn.dataset.formulaProof;$('button',d).onclick=()=>d.remove();document.body.append(d);d.showModal();});decorate(root);
}
function sourceLinks(sources){return (sources||[]).map(([id,where])=>`<a href="#/original/${E(id)}">${E(id)} · ${E(where)}</a>`).join('；');}
const patterns=[];for(const t of termById.values())for(const s of new Set([t.en,t.zh,...(t.aliases||[])]))if(s&&s.length>1)patterns.push([s,t.id]);patterns.sort((a,b)=>b[0].length-a[0].length);const seen=new Set(),unique=patterns.filter(([s])=>{const k=s.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}),lookup=new Map(unique.map(([s,id])=>[s.toLowerCase(),id]));const rx=unique.length?new RegExp(unique.map(([s])=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'gi'):null;
function decorate(root){if(!root||!rx)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;return p&&n.nodeValue.trim()&&p.closest('.prose,.original-text,.study-narrative,.study-overview,.paragraph-zh')&&!p.closest('a,button,code,pre,script,style,math,.term-token,.formula-raw,.running-metadata,.translation-label')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const str=node.nodeValue,matches=[...str.matchAll(rx)].filter(m=>{const ascii=/^[A-Za-z]/.test(m[0]);return !ascii||!(/[A-Za-z0-9_]/.test(str[m.index-1]||'')||/[A-Za-z0-9_]/.test(str[m.index+m[0].length]||''));});if(!matches.length)continue;const f=document.createDocumentFragment();let end=0;for(const m of matches){f.append(str.slice(end,m.index));const s=document.createElement('span');s.className='term-token';s.dataset.term=lookup.get(m[0].toLowerCase());s.textContent=m[0];s.tabIndex=0;s.setAttribute('role','button');s.setAttribute('aria-haspopup','dialog');s.setAttribute('aria-label',m[0]+'：查看术语解释');f.append(s);end=m.index+m[0].length;}f.append(str.slice(end));node.replaceWith(f);}}
function closeTerm(){popup?.remove();popup=null;$$('.term-token[aria-expanded="true"]').forEach(x=>x.setAttribute('aria-expanded','false'));}
function openTerm(token){if(getSelection()?.toString().trim())return;const term=termById.get(token.dataset.term);if(!term)return;const previous=popup?.dataset.term;closeTerm();if(previous===term.id)return;token.setAttribute('aria-expanded','true');popup=document.createElement('aside');popup.id='term-explainer';popup.dataset.term=term.id;popup.setAttribute('role','dialog');popup.setAttribute('aria-labelledby','term-title');popup.innerHTML=`<div class="term-head"><h3 id="term-title">${E(term.zh)}</h3><button type="button" aria-label="关闭术语解释">×</button></div><div class="term-en">${E(term.en)}</div><p>${E(term.definition)}</p>${term.caution?`<p class="term-caution">注意：${E(term.caution)}</p>`:''}<small>教学释义 · 依据：${sourceLinks(term.sources)}</small>${term.more?`<p class="term-more"><a href="#/${E(term.more)}">进入完整方法讲解 →</a></p>`:''}`;document.body.append(popup);$('button',popup).onclick=closeTerm;const r=token.getBoundingClientRect(),w=Math.min(360,innerWidth-24);popup.style.width=w+'px';const h=popup.getBoundingClientRect().height;popup.style.left=Math.max(12,Math.min(innerWidth-w-12,r.left))+'px';popup.style.top=Math.max(12,Math.min(innerHeight-h-12,r.bottom+8))+'px';}
document.addEventListener('pointerdown',e=>{if(popup&&!popup.contains(e.target)&&!e.target.closest('.term-token'))closeTerm();},true);
document.addEventListener('click',e=>{const t=e.target.closest?.('.term-token');if(t){e.stopPropagation();openTerm(t);}},false);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTerm();const t=e.target.closest?.('.term-token');if(t&&['Enter',' '].includes(e.key)){e.preventDefault();openTerm(t);}});
function narrative(s,id){return String(s||'').split(/\n\n/).map((p,i)=>`<p id="${E(id)}-${i}" data-block="${E(id)}-${i}" data-language="zh-CN">${E(p)}</p>`).join('');}
function enhanceLesson(){const root=$('#view .reader');if(!root||root.dataset.frameworkReady)return;root.dataset.frameworkReady='true';const id=location.hash.replace(/^#\//,'').split('/')[0],f=S.frameworks?.papers?.[id];if(!f){decorate(root);return;}const originals=new Map($$('section[id^="s"]',root).filter(x=>/^s\d+$/.test(x.id)).map(x=>[Number(x.id.slice(1)),x]));if(!f.stages.every(g=>g.details.every(i=>originals.has(i)))){console.warn('Framework skipped: source section mismatch',id);decorate(root);return;}
const overview=document.createElement('div');overview.className='study-overview';overview.id='research-framework';overview.innerHTML=`<span class="eyebrow">先看整篇论证 / NOT A LIST OF TOOLS</span><h2>${E(f.question)}</h2><p>${E(f.position)}</p><div class="argument-chain">${f.chain.map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${E(x)}</span></div>`).join('')}</div><p class="study-input"><strong>进入本篇之前：</strong>${E(f.before)}</p><p class="study-output"><strong>读完本篇之后：</strong>${E(f.after)}</p><a href="#/study-map">← 回到全部论文的研究框架</a>`;$('.articlehead',root).after(overview);
const host=document.createElement('div');host.className='framework-reading';overview.after(host);const used=new Set();f.stages.forEach((g,i)=>{const section=document.createElement('section');section.id='framework-'+i;section.className='study-stage';section.innerHTML=`<span class="kind">论证第${i+1}步</span><h2>${i+1}. ${E(g.title)}</h2><div class="study-narrative">${narrative(g.text,'framework-'+id+'-'+i)}</div><p class="stage-checkpoint"><strong>这一层的验收：</strong>${E(g.checkpoint)}</p><details class="method-drilldown"><summary>展开这一层的原有精读细节 · ${g.details.length}节</summary><div class="drilldown-content"></div></details>`;const box=$('.drilldown-content',section);for(const j of g.details){box.append(originals.get(j));used.add(j);}host.append(section);});for(const [j,sec] of originals)if(!used.has(j))host.append(sec);
const next=document.createElement('div');next.className='study-next';next.innerHTML=`<strong>从这一篇接到下一步</strong><p>${E(f.after)}</p><a href="#/${E(f.next)}">继续这条研究线 →</a>`;host.append(next);
const toc=`<a href="#/${E(id)}/research-framework">整篇研究框架</a>`+f.stages.map((g,i)=>`<a href="#/${E(id)}/framework-${i}">${i+1}. ${E(g.title)}</a>`).join('')+`<a href="#/${E(id)}/self-test">自测与笔记</a><a href="#/study-map">全部论文研究框架</a>`;const side=$('.toc');if(side)side.innerHTML='<strong>RESEARCH ARGUMENT</strong>'+toc;const mobile=$('.mobiletoc',root);if(mobile)mobile.innerHTML='<summary>按论证步骤阅读</summary>'+toc;
const target=location.hash.replace(/^#\//,'').split('/')[1];if(target)reveal(target);decorate(root);
}
async function bounded(stream,max){const reader=stream.getReader(),parts=[];let total=0;for(;;){const r=await reader.read();if(r.done)break;total+=r.value.length;if(total>max){await reader.cancel();throw Error('译文包展开后超过安全上限');}parts.push(r.value);}return new Uint8Array(await new Blob(parts).arrayBuffer());}
async function unzipTranslation(bytes){const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break;}if(end<0)throw Error('ZIP目录无效');let pos=view.getUint32(end+16,true),count=view.getUint16(end+10,true);if(count>100)throw Error('ZIP文件过多');for(let i=0;i<count;i++){if(view.getUint32(pos,true)!==0x02014b50)throw Error('ZIP目录错误');const method=view.getUint16(pos+10,true),size=view.getUint32(pos+20,true),usize=view.getUint32(pos+24,true),nl=view.getUint16(pos+28,true),el=view.getUint16(pos+30,true),cl=view.getUint16(pos+32,true),off=view.getUint32(pos+42,true),name=new TextDecoder().decode(bytes.slice(pos+46,pos+46+nl));pos+=46+nl+el+cl;if(!name.endsWith('.papertranslations'))continue;if(size>30e6||usize>30e6||name.split('/').includes('..'))throw Error('译文ZIP成员无效');if(view.getUint32(off,true)!==0x04034b50)throw Error('ZIP头无效');const start=off+30+view.getUint16(off+26,true)+view.getUint16(off+28,true),data=bytes.slice(start,start+size);if(method===0)return data;if(method===8)return bounded(new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw')),30e6);throw Error('请先解压ZIP，再导入其中的.papertranslations文件');}throw Error('ZIP中没有中文对照包');}
async function importTranslations(file){if(file.size>30e6)throw Error('译文包不得超过30MB');let bytes=new Uint8Array(await file.arrayBuffer());if(bytes[0]===80&&bytes[1]===75)bytes=await unzipTranslation(bytes);if(bytes[0]===31&&bytes[1]===139)bytes=await bounded(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip')),60e6);const data=JSON.parse(new TextDecoder().decode(bytes));if(data.schema!=='paper.private.translations.v3'||!Array.isArray(data.translations)||data.translations.length>100)throw Error('不是匹配的中文对照包');let count=0;for(const t of data.translations){if(!/^[a-f0-9]{64}$/.test(t.sourceHash)||t.schema!=='paper.translations.v3'||!t.blocks||typeof t.blocks!=='object'||Array.isArray(t.blocks)||Object.keys(t.blocks).length>50000)throw Error('译文结构无效');for(const [id,v] of Object.entries(t.blocks)){if(!/^[\w:-]+$/.test(id)||typeof v.zh!=='string'||v.zh.length>60000||!/^[a-f0-9]{64}$/.test(v.sourceTextHash))throw Error('段落译文无效');}await io('put',{id:t.sourceHash,payload:t,importedAt:new Date().toISOString()});count++;}return count;}
function chooseTranslation(){const f=document.createElement('input');f.type='file';f.accept='.papertranslations,.json,.zip';f.onchange=async()=>{if(!f.files[0])return;try{const count=await importTranslations(f.files[0]);alert(`已导入${count}篇中文对照。仅存本机，不上传；重新打开对应原文即可阅读。`);const parts=location.hash.replace(/^#\//,'').split('/');if(parts[0]==='original')await window.PaperReader.route('original',parts);}catch(e){alert('导入未完成：'+e.message);}};f.click();}
function leave(){++ticket;current=null;layout=null;translation=null;closeTerm();$('#study-side-controls')?.remove();}
window.PaperStudy={loadOriginal,blockHTML,enhanceOriginal,enhanceLesson,decorateTerms:decorate,closeTerm,reveal,leave,importTranslations,chooseTranslation};
})();
