/* Private GitHub vault. Authorization is held in memory only, never in any backup.
   A successful local save is NOT a successful remote save. No public-repository writes. */
(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TRACK={
 'paper-lab-reader-v2':['books','files','annotations','positions'],
 'paper-translations-v3':['translations'],
 'paper-workspace-v4':['references','workbooks','terms'],
 'paper-comfort-v5':['tags','drafts','conflicts']
};
const KEY='paper-lab-learning-v1', PREFIX='private/paper-sync/v5/', CHUNK=524288, MAX_META=100000000;
const encoder=new TextEncoder(),decoder=new TextDecoder(),dbs=new Map(),fileMemo=new Map();
let authorization='',config=null,busy=false,applying=false,dirty=true,timer=null,lastWrite=0,connection=0;
let status={state:'local-only',message:'本地保存 · 尚未连接 GitHub',confirmedAt:null,commit:null,progress:''};
const confirmedObjects=new Set();
const device=(()=>{try{let x=localStorage.getItem('paper-sync-device-v5');if(!x){x=crypto.randomUUID();localStorage.setItem('paper-sync-device-v5',x);}return x;}catch{return crypto.randomUUID();}})();
const clone=x=>JSON.parse(JSON.stringify(x));
function canonical(x){if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';return JSON.stringify(x);}
async function sha(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',typeof bytes==='string'?encoder.encode(bytes):bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');}
function base64(bytes){let text='';for(let i=0;i<bytes.length;i+=32768)text+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(text);}
function unbase64(text){return Uint8Array.from(atob(text.replace(/\s/g,'')),c=>c.charCodeAt(0));}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const key=(db,store,id)=>JSON.stringify([db,store,id]);
const deleted=()=>({hash:'deleted',deleted:true});
const hashOf=e=>e?.hash||'absent';
function openDB(name){if(dbs.has(name))return dbs.get(name);const promise=new Promise((ok,no)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>{const stores=TRACK[name]||['receipts'];for(const store of stores)if(!r.result.objectStoreNames.contains(store))r.result.createObjectStore(store,{keyPath:'id'});};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error);});dbs.set(name,promise);return promise;}
async function io(db,store,method,value){const d=await openDB(db);return new Promise((ok,no)=>{const t=d.transaction(store,['get','getAll'].includes(method)?'readonly':'readwrite'),r=t.objectStore(store)[method](value);let v;r.onsuccess=()=>v=r.result;t.oncomplete=()=>ok(v);t.onabort=t.onerror=()=>no(t.error||Error('本地存储失败'));});}
const receipt=(method,value)=>io('paper-sync-receipts-v5','receipts',method,value);
function vaultID(){return config.repository+'@'+config.branch;}
function setStatus(next){status={...status,...next};const b=$('#sync-status');if(b){b.dataset.state=status.state;b.textContent={synced:'云端已确认',syncing:'同步中…',pending:'等待同步',offline:'离线待同步',error:'同步失败',connecting:'连接中…','local-only':'仅本地'}[status.state]||'同步';b.title=status.message;b.setAttribute('aria-label','GitHub 同步：'+status.message);}const p=$('#vault-status');if(p)p.textContent=status.message+(status.progress?' · '+status.progress:'');const c=$('#vault-confirmed');if(c)c.textContent=status.confirmedAt?'上次 GitHub 确认：'+new Date(status.confirmedAt).toLocaleString():'尚无 GitHub 确认记录';document.dispatchEvent(new CustomEvent('paper-sync-status',{detail:{...status}}));}
function changed(store){if(applying)return;if(store==='files'||store==='books'){fileMemo.clear();try{localStorage.setItem('paper-sync-file-revision-v5',Date.now()+'-'+device);}catch{}}dirty=true;setStatus({state:authorization?(navigator.onLine?'pending':'offline'):'local-only',message:authorization?'本地已保存，尚有更改等待 GitHub 确认':'本地已保存；连接 GitHub 后才能跨设备恢复',progress:''});clearTimeout(timer);if(authorization&&navigator.onLine)timer=setTimeout(()=>sync().catch(()=>{}),8000);}
function checkConfig(c){if(!c||!/^[-\w]+\/[-.\w]+$/.test(c.repository)||!/^paper-user-data(?:-test-\d+)?$/.test(c.branch))throw Error('需要 owner/repository 格式的私有仓库；数据分支必须为 paper-user-data。');return {repository:c.repository,branch:c.branch};}
function checkConnection(ticket){if(!authorization||ticket!==connection)throw Error('同步连接已关闭；本地数据保留。');}
async function api(path,{method='GET',body,missing=false}={}){
 if(!authorization||!config)throw Error('请先在同步中心连接 GitHub。');if(!navigator.onLine)throw Error('当前离线，本地更改保留待同步。');
 if(!path.startsWith('/repos/'+config.repository+'/'))throw Error('拒绝访问同步仓库之外的路径');
 if(method!=='GET'){const gap=1050-(Date.now()-lastWrite);if(gap>0)await sleep(gap);lastWrite=Date.now();}
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),45000);
 try{const response=await fetch('https://api.github.com'+path,{method,headers:{Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28',Authorization:'Bearer '+authorization},body:body?JSON.stringify(body):undefined,credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer',signal:controller.signal});
 if(response.status===404&&missing)return null;
 if(!response.ok){const error=Error(response.status===401?'GitHub 授权失效，请重新连接；本地数据未删除。':response.status===403||response.status===429?'GitHub 拒绝请求或限流，请检查权限并稍后重试；未标记同步完成。':'GitHub 请求失败（HTTP '+response.status+'）');error.http=response.status;throw error;}
 return response.status===204?null:await response.json();
 }catch(e){if(e.name==='AbortError')throw Error('GitHub 请求超时；本地更改和已上传分块保留。');throw e;}finally{clearTimeout(timeout);}}
const route=path=>'/repos/'+config.repository+'/'+path;
async function verifyVault(){const info=await api(route(''));if(info.private!==true)throw Error('拒绝同步：目标是公开仓库。私人笔记和论文只能进入私有仓库。');const branch=await api(route('branches/'+encodeURIComponent(config.branch)),{missing:true});if(!branch)throw Error('私有数据分支尚不存在，请按同步中心说明创建；不向网站主分支写入。');if(info.permissions&&info.permissions.push===false)throw Error('此授权没有仓库写入权限。');}
async function getFile(path,missing=false){if(!path.startsWith(PREFIX)||path.includes('..'))throw Error('不允许的同步文件路径');return api(route('contents/'+path)+'?ref='+encodeURIComponent(config.branch),{missing});}
async function putFile(path,bytes,priorSHA){if(!path.startsWith(PREFIX)||path.includes('..'))throw Error('不允许的同步文件路径');return api(route('contents/'+path),{method:'PUT',body:{message:'Paper private vault checkpoint [skip ci]',branch:config.branch,content:base64(bytes),...(priorSHA?{sha:priorSHA}:{})}});}
async function objectBytes(hash){if(!/^[a-f0-9]{64}$/.test(hash))throw Error('无效分块哈希');const r=await getFile(PREFIX+'objects/'+hash+'.bin');if(!r||r.encoding!=='base64'||typeof r.content!=='string')throw Error('云端分块不可读取');const bytes=unbase64(r.content);if(bytes.length>CHUNK||await sha(bytes)!==hash)throw Error('云端分块校验失败；未恢复损坏数据');return bytes;}
async function ensureObject(hash,bytes){const id=vaultID()+'|object|'+hash;if(confirmedObjects.has(id))return;const path=PREFIX+'objects/'+hash+'.bin';let prior=await getFile(path,true);if(prior){if(prior.encoding!=='base64'||await sha(unbase64(prior.content))!==hash)throw Error('云端已有分块内容与哈希不一致');}else{try{await putFile(path,bytes);}catch(e){if(![409,422].includes(e.http))throw e;prior=await getFile(path,true);if(!prior||prior.encoding!=='base64'||await sha(unbase64(prior.content))!==hash)throw e;}}confirmedObjects.add(id);}
async function describeBlob(row){const cached=fileMemo.get(row.id);if(cached&&cached.value.bytes===row.blob.size&&cached.value.mime===row.blob.type)return cached;const bytes=new Uint8Array(await row.blob.arrayBuffer());if(bytes.length>120000000)throw Error('单份导入附件超过120MB，请先拆分；笔记仍在本地。');const parts=[];for(let i=0;i<bytes.length;i+=CHUNK)parts.push(await sha(bytes.subarray(i,i+CHUNK)));const result={value:{id:row.id,$blob:true,bytes:bytes.length,mime:row.blob.type,sha256:await sha(bytes),parts},blob:row.blob};fileMemo.set(row.id,result);return result;}
async function capture(){const entries={},blobs=new Map();for(const [db,stores] of Object.entries(TRACK))for(const store of stores){const rows=await io(db,store,'getAll');for(const row of rows){let value=clone(row);if(store==='files'){if(!(row.blob instanceof Blob))throw Error('本机附件缺失，不能声明完整同步');const f=await describeBlob(row);value=f.value;blobs.set(value.sha256,f.blob);}entries[key(db,store,row.id)]={hash:await sha(canonical(value)),value};}}
 let learning={};try{learning=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{throw Error('旧版学习笔记格式损坏，请先导出备份再恢复。');}
 for(const [section,value] of Object.entries(learning)){if(['notes','done','positions'].includes(section)){for(const [id,data] of Object.entries(value||{}))entries[key('learning',section,id)]={hash:await sha(canonical(data)),value:data};}else entries[key('learning','settings',section)]={hash:await sha(canonical(value)),value};}
 for(const setting of ['paper-reader-settings-v2','paper-study-v3']){const value=localStorage.getItem(setting);if(value!==null)entries[key('settings','localStorage',setting)]={hash:await sha(canonical(value)),value};}
 return {entries,blobs};}
function validKey(k){let a;try{a=JSON.parse(k);}catch{throw Error('云端记录索引损坏');}if(!Array.isArray(a)||a.length!==3||a.some(x=>typeof x!=='string')||a[2].length>600||['__proto__','constructor','prototype'].includes(a[2]))throw Error('云端记录键不安全');const [db,store,id]=a;if(db==='learning'){if(!['notes','done','positions','settings'].includes(store))throw Error('无效笔记类别');}else if(db==='settings'){if(store!=='localStorage'||!['paper-reader-settings-v2','paper-study-v3'].includes(id))throw Error('不允许的设置');}else if(!TRACK[db]?.includes(store))throw Error('云端试图写入未授权的数据表');return a;}
async function validate(entries){if(!entries||Array.isArray(entries)||typeof entries!=='object'||Object.keys(entries).length>100000)throw Error('云端数据规模或结构错误');for(const [k,e] of Object.entries(entries)){const [db,store,id]=validKey(k);if(!e||typeof e.hash!=='string')throw Error('记录版本无效');if(e.deleted){if(e.hash!=='deleted')throw Error('删除标记无效');continue;}if(await sha(canonical(e.value))!==e.hash)throw Error('记录完整性校验失败');const v=e.value;if(TRACK[db]&&(!v||typeof v!=='object'||v.id!==id))throw Error('记录身份与索引不一致');if(store==='files'){if(!v.$blob||!Number.isSafeInteger(v.bytes)||v.bytes<0||v.bytes>120000000||!Array.isArray(v.parts)||v.parts.length!==Math.ceil(v.bytes/CHUNK)||v.parts.some(h=>!/^[a-f0-9]{64}$/.test(h))||!/^[a-f0-9]{64}$/.test(v.sha256)||typeof v.mime!=='string'||v.mime.length>200)throw Error('云端附件清单不正确');}if(store==='annotations'&&(!Array.isArray(v.segments)||typeof v.comment!=='string'||v.comment.length>40000))throw Error('批注结构错误');if(store==='books'&&(!Array.isArray(v.pages)||v.pages.length>400||!v.local))throw Error('导入论文结构错误');if(db==='learning'&&store==='notes'&&(typeof v!=='string'||v.length>1000000))throw Error('笔记字段错误');}}
async function merge(base,local,remote){const result={},conflicts=[];for(const k of new Set([...Object.keys(base),...Object.keys(local),...Object.keys(remote)])){const b=base[k]||'absent',l=local[k]||(b!=='absent'?deleted():undefined),r=remote[k];const lh=hashOf(l),rh=hashOf(r);
 if(lh===rh){if(l)result[k]=l;continue;}if(lh===b){if(r)result[k]=r;continue;}if(rh===b){if(l)result[k]=l;continue;}if(!r&&b==='absent'){if(l)result[k]=l;continue;}if(!l&&b==='absent'){if(r)result[k]=r;continue;}
 const id='conflict-'+(await sha(k+'|'+[lh,rh].sort().join('|'))).slice(0,32),value={id,key:k,local:l||deleted(),remote:r||deleted(),createdAt:new Date().toISOString(),resolved:false};
 // Never destroy a surviving edit in a simultaneous edit/delete conflict.
 result[k]=r&&!r.deleted?r:(l||deleted());const ck=key('paper-comfort-v5','conflicts',id);if(!local[ck]&&!remote[ck]){result[ck]={hash:await sha(canonical(value)),value};conflicts.push(id);}
 }return {entries:result,conflicts};}
function validateReferences(entries){for(const [k,e] of Object.entries(entries)){if(e.deleted)continue;const [db,store,id]=validKey(k),v=e.value;
 if(db==='paper-lab-reader-v2'&&store==='books'){const file=entries[key(db,'files',id+'/original')];if(!file||file.deleted||file.value.sha256!==v.sourceHash)throw Error('导入论文的原件缺失或与书目哈希不匹配；未声明完整同步');for(const page of v.pages){if(page.snapshot){const image=entries[key(db,'files',page.snapshot)];if(!page.local||!image||image.deleted||!page.snapshot.startsWith(id+'/'))throw Error('导入论文的原页图片缺失或关联错误');}}}
 if(db==='paper-comfort-v5'&&store==='tags'){if(typeof v.label!=='string'||v.label.length>100||typeof v.text!=='string'||v.text.length>15000||v.href&&!window.PaperComfort.safeLink(v.href))throw Error('云端标签内容或链接不安全');}
 if(db==='settings'&&(typeof v!=='string'||v.length>10000))throw Error('阅读设置字段无效');
 if(db==='paper-workspace-v4'&&store==='references'&&v.landing&&!window.PaperWorkspace.safeURL(v.landing))throw Error('书目链接不安全');
}}
async function readRemote(){const index=await getFile(PREFIX+'index.json',true);if(!index)return {entries:{},sha:null};if(index.encoding!=='base64')throw Error('云端索引格式错误');const meta=JSON.parse(decoder.decode(unbase64(index.content)));if(meta.schema!=='paper.sync.v5'||!Array.isArray(meta.parts)||meta.parts.length>200||meta.bytes>MAX_META||meta.bytes<0||!['gzip','json'].includes(meta.codec))throw Error('云端索引不受支持');let chunks=[];for(const h of meta.parts)chunks.push(await objectBytes(h));const joined=new Blob(chunks);if(joined.size!==meta.bytes||await sha(await joined.arrayBuffer())!==meta.hash)throw Error('云端索引分块不完整');let stream=joined.stream();if(meta.codec==='gzip'){if(!window.DecompressionStream)throw Error('此浏览器不支持压缩同步，请更新浏览器。');stream=stream.pipeThrough(new DecompressionStream('gzip'));}const reader=stream.getReader();let size=0,parts=[];for(;;){const x=await reader.read();if(x.done)break;size+=x.value.length;if(size>MAX_META){await reader.cancel();throw Error('云端数据解压超过安全上限');}parts.push(x.value);}const payload=JSON.parse(await new Blob(parts).text());if(payload.schema!=='paper.sync.records.v5')throw Error('云端记录版本不受支持');await validate(payload.entries);validateReferences(payload.entries);return {entries:payload.entries,sha:index.sha,index:meta};}
async function uploadFiles(entries,blobs,ticket){const files=Object.values(entries).filter(e=>!e.deleted&&e.value?.$blob),chunks=files.reduce((n,e)=>n+e.value.parts.length,0);let done=0;for(const e of files){const value=e.value,blob=blobs.get(value.sha256);if(!blob){done+=value.parts.length;continue;}for(let i=0;i<value.parts.length;i++){checkConnection(ticket);setStatus({progress:'附件分块 '+(++done)+'/'+chunks});const bytes=new Uint8Array(await blob.slice(i*CHUNK,(i+1)*CHUNK).arrayBuffer());await ensureObject(value.parts[i],bytes);}}}
async function writeRemote(entries,priorSHA,ticket){let bytes=encoder.encode(JSON.stringify({schema:'paper.sync.records.v5',entries}));if(bytes.length>MAX_META)throw Error('同步元数据超过100MB，请分库保存。');let codec='json';if(window.CompressionStream){bytes=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer());codec='gzip';}const parts=[];for(let i=0;i<bytes.length;i+=CHUNK){checkConnection(ticket);const chunk=bytes.subarray(i,i+CHUNK),hash=await sha(chunk);await ensureObject(hash,chunk);parts.push(hash);}const index={schema:'paper.sync.v5',codec,hash:await sha(bytes),bytes:bytes.length,parts,writer:device,at:new Date().toISOString()};checkConnection(ticket);const result=await putFile(PREFIX+'index.json',encoder.encode(JSON.stringify(index)),priorSHA);return {index,commit:result.commit?.sha};}
async function materialize(entries,local,ticket){const staged=new Map();let i=0;const needed=Object.entries(entries).filter(([k,e])=>!e.deleted&&e.value?.$blob&&local[k]?.value?.sha256!==e.value.sha256);for(const [k,e] of needed){checkConnection(ticket);setStatus({progress:'恢复附件 '+(++i)+'/'+needed.length});const v=e.value,chunks=[];for(const h of v.parts)chunks.push(await objectBytes(h));const blob=new Blob(chunks,{type:v.mime});if(blob.size!==v.bytes||await sha(await blob.arrayBuffer())!==v.sha256)throw Error('附件恢复校验失败；现有原件未替换');staged.set(k,{id:v.id,blob});}return staged;}
async function apply(entries,captured,staged,ticket){const fresh=await capture();let skipped=0;const learning=JSON.parse(localStorage.getItem(KEY)||'{}');applying=true;
 try{for(const [k,e] of Object.entries(entries)){checkConnection(ticket);if(hashOf(fresh.entries[k])!==hashOf(captured[k])){skipped++;continue;}if(hashOf(fresh.entries[k])===e.hash)continue;const [db,store,id]=validKey(k);
 if(db==='learning'){if(store==='settings'){if(e.deleted)delete learning[id];else learning[id]=e.value;}else{learning[store]||={};if(e.deleted)delete learning[store][id];else learning[store][id]=e.value;}}
 else if(db==='settings'){if(e.deleted)localStorage.removeItem(id);else localStorage.setItem(id,e.value);}
 else if(e.deleted)await io(db,store,'delete',id);
 else if(store==='files'){const value=staged.get(k);if(!value)throw Error('缺少经校验的待恢复附件');await io(db,store,'put',value);fileMemo.set(id,{value:e.value,blob:value.blob});}
 else await io(db,store,'put',e.value);
 }
 localStorage.setItem(KEY,JSON.stringify(learning));window.dispatchEvent(new CustomEvent('paper-sync-applied',{detail:{skipped}}));return skipped;
 }finally{applying=false;}}
async function perform(){if(busy)return {...status};const ticket=connection;busy=true;dirty=false;setStatus({state:'syncing',message:'正在核对私有仓库与本机版本，尚未完成',progress:''});
 try{await verifyVault();checkConnection(ticket);const snapshot=await capture(),saved=await receipt('get',vaultID()),base=saved?.base||{};let successful=null,merged=null;
 for(let attempt=0;attempt<3;attempt++){const remote=await readRemote();checkConnection(ticket);merged=await merge(base,snapshot.entries,remote.entries);await validate(merged.entries);validateReferences(merged.entries);await uploadFiles(snapshot.entries,snapshot.blobs,ticket);await uploadFiles(merged.entries,snapshot.blobs,ticket);
 if(canonical(merged.entries)===canonical(remote.entries)&&remote.sha){successful={index:remote.index,commit:saved?.commit||null};break;}
 try{successful=await writeRemote(merged.entries,remote.sha,ticket);break;}catch(e){if(![409,422].includes(e.http)||attempt===2)throw e;setStatus({progress:'另一设备刚写入，重新合并（'+(attempt+1)+'/3）'});await sleep(500);}}
 if(!successful)throw Error('并发写入未完成；等待重试。');
 const staged=await materialize(merged.entries,snapshot.entries,ticket),skipped=await apply(merged.entries,snapshot.entries,staged,ticket);checkConnection(ticket);const confirmedAt=new Date().toISOString();await receipt('put',{id:vaultID(),base:Object.fromEntries(Object.entries(merged.entries).map(([k,e])=>[k,e.hash])),confirmedAt,commit:successful.commit});
 dirty=dirty||skipped>0;setStatus({state:dirty?'pending':'synced',message:dirty?'云端检查点已保存；同步期间的新修改继续排队':'GitHub 已确认本次数据；本机副本已核对'+(merged.conflicts.length?'，冲突版本已保留，请处理':''),confirmedAt,commit:successful.commit,progress:''});return {...status};
 }catch(e){dirty=true;setStatus({state:authorization?(navigator.onLine?'error':'offline'):'local-only',message:e.message,progress:''});throw e;
 }finally{busy=false;}}
async function sync(){clearTimeout(timer);if(!authorization)throw Error('尚未连接 GitHub；不能将本地保存显示为云端成功。');return navigator.locks?navigator.locks.request('paper-vault-'+vaultID(),perform):perform();}
async function connect(c,token){if(busy)throw Error('上一次同步仍在结束，请稍候再连接。');const next=checkConfig(c);if(typeof token!=='string'||! /^(?:github_pat_|gh[opusr]_)[A-Za-z0-9_]{16,}$/.test(token.trim()))throw Error('这里需要 GitHub 授权令牌，不是校园账号、密码或仓库地址。');connection++;confirmedObjects.clear();authorization=token.trim();config=next;setStatus({state:'connecting',message:'验证私有仓库权限…',progress:''});try{await verifyVault();localStorage.setItem('paper-sync-config-v5',JSON.stringify(next));const r=await receipt('get',vaultID());setStatus({state:'pending',message:'已连接私有数据分支；首次同步会合并本机旧笔记',confirmedAt:r?.confirmedAt||null,commit:r?.commit||null});return await sync();}catch(e){authorization='';setStatus({state:'error',message:e.message});throw e;}}
function disconnect(){connection++;authorization='';clearTimeout(timer);setStatus({state:'local-only',message:'GitHub 连接已断开；本地与已上传数据均保留。',progress:''});}
async function resolveConflict(id,choice){const v=await io('paper-comfort-v5','conflicts','get',id);if(!v)throw Error('冲突记录不存在');const entry=choice==='local'?v.local:v.remote;const [db,store,keyID]=validKey(v.key);if(db==='learning'){const x=JSON.parse(localStorage.getItem(KEY)||'{}');if(store==='settings'){if(entry.deleted)delete x[keyID];else x[keyID]=entry.value;}else{x[store]||={};if(entry.deleted)delete x[store][keyID];else x[store][keyID]=entry.value;}localStorage.setItem(KEY,JSON.stringify(x));window.dispatchEvent(new Event('paper-sync-applied'));}else if(TRACK[db]&&store!=='files'){await io(db,store,entry.deleted?'delete':'put',entry.deleted?keyID:entry.value);}else throw Error('附件或设置冲突请先导出完整备份，再在相应界面核对；两个版本仍保留。');await io('paper-comfort-v5','conflicts','put',{...v,resolved:true,resolution:choice,resolvedAt:new Date().toISOString()});changed(store);}
async function render(){let saved={repository:'1337816143/My-Evolution',branch:'paper-user-data'};try{saved={...saved,...JSON.parse(localStorage.getItem('paper-sync-config-v5')||'{}')};}catch{}
 $('#view').innerHTML=`<header class="pagehead"><span class="eyebrow">PRIVATE GITHUB VAULT</span><h1>笔记与论文，同步到你的私有仓库</h1><p>本地优先保存；只有 GitHub 返回成功，才显示云端已确认。换设备连接同一仓库和数据分支，自动恢复。</p></header><section class="card sync-panel"><p id="vault-status" role="status"></p><p id="vault-confirmed"></p><form id="vault-connect"><label>私有仓库<input name="repository" required value="${E(saved.repository)}" autocomplete="off"></label><label>数据分支<input name="branch" required value="${E(saved.branch)}" autocomplete="off"></label><label>GitHub 会话授权<input name="authorization" type="password" required autocomplete="off" spellcheck="false" placeholder="GitHub fine-grained token；不要输入学校密码"></label><p class="muted">授权只存在当前页面内存，断开或刷新后消失；不会写入本地存储、同步包或仓库。优先使用短有效期、仅选目标私有仓库、Contents 读写权限的 fine-grained token。无需对网站主分支授权额外工作流权限。</p><div class="actions"><button type="submit" class="primary">连接并合并旧笔记</button><button id="vault-now" type="button">立即同步</button><button id="vault-disconnect" type="button">断开</button><button id="vault-refresh" type="button">刷新已恢复的阅读内容</button></div></form><details><summary>首次设置与同步范围</summary><p>数据分支 paper-user-data 与网站代码分开，数据路径为 private/paper-sync/v5/。仓库必须私有，公开仓库会被拒绝。此版本不包含已部署的 GitHub OAuth 后端，所以每次新页面会话需要重新授权，不会假装已免登录连接。</p><p>同步包括原文划线／批注、独立便签、旧版整篇笔记与进度、阅读位置、个人文献库、工作表、自定义术语与标签、草稿、译文以及已导入的原始文件和图像。公开网站缓存不重复上传。附件按哈希分块；首次大量附件可能受 GitHub 限流，需要保持页面打开或稍后重试。</p><p>同一条记录在两台设备同时修改时，保留冲突两份，不静默覆盖。离线期间本地保存，在线且会话仍连接时继续同步。修改后未显示“云端已确认”前，不要清除本机数据。</p><a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">在 GitHub 创建受限授权 ↗</a></details><p>仍建议定期使用“我的文献库 → 完整个人备份”保留独立副本。GitHub 存储有容量与接口限制，不承诺无限附件或永不丢失。</p></section><section class="card"><h2>需核对的冲突</h2><div id="vault-conflicts"></div></section>`;
 $('#vault-connect').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,token=f.elements.authorization.value;f.elements.authorization.value='';try{await connect({repository:f.elements.repository.value.trim(),branch:f.elements.branch.value.trim()},token);await drawConflicts();}catch(e){setStatus({state:'error',message:e.message});}};
 $('#vault-now').onclick=()=>sync().then(drawConflicts).catch(e=>setStatus({state:'error',message:e.message}));$('#vault-disconnect').onclick=disconnect;$('#vault-refresh').onclick=()=>window.PaperReader.navigate('#/my-library');setStatus({});await drawConflicts();}
async function drawConflicts(){const root=$('#vault-conflicts');if(!root)return;const rows=(await io('paper-comfort-v5','conflicts','getAll')).filter(x=>!x.resolved);root.textContent='';if(!rows.length){root.textContent='暂无未处理冲突。';return;}for(const row of rows){const box=document.createElement('details'),heading=document.createElement('summary');heading.textContent=JSON.parse(row.key).slice(1).join(' · ');box.append(heading);for(const side of ['local','remote']){const pre=document.createElement('pre');pre.textContent=(side==='local'?'此设备版本':'同步时的云端版本')+'\n'+JSON.stringify(row[side]?.deleted?'已删除':row[side]?.value,null,2);box.append(pre);const button=document.createElement('button');button.textContent=side==='local'?'使用此设备版本':'使用云端版本';button.onclick=()=>resolveConflict(row.id,side).then(drawConflicts).catch(e=>setStatus({message:e.message}));box.append(button);}root.append(box);}}
addEventListener('online',()=>{if(authorization){setStatus({state:'pending',message:'网络恢复，准备核对 GitHub'});sync().catch(()=>{});}});addEventListener('offline',()=>{if(authorization)setStatus({state:'offline',message:'离线：继续本地保存，联网后再同步'});});
setInterval(()=>{if(authorization&&!busy&&navigator.onLine&&document.visibilityState==='visible')sync().catch(()=>{});},60000);
addEventListener('beforeunload',e=>{if(authorization&&(busy||dirty)){e.preventDefault();e.returnValue='';}});
addEventListener('storage',e=>{if(e.key==='paper-sync-file-revision-v5'){fileMemo.clear();changed('other-tab-files');}});
window.PaperSync={connect,disconnect,sync,changed,render,capture,merge,validate,resolveConflict,status:()=>({...status,connected:!!authorization,busy,dirty,configuration:config?{...config}:null}),isApplying:()=>applying,version:'5.0'};
})();
